use crate::model::problem::{ApproachMeta, Example, Problem, ProblemDetails};
use crate::model::taxonomy::{Category, Difficulty};

pub fn get_details(problem: Problem) -> Option<ProblemDetails> {
    match problem {
        Problem::BinarySearch => Some(ProblemDetails {
                id: 704, title: "Binary Search", difficulty: Difficulty::Easy, category: Category::BinarySearch,
                statement: "Given sorted array nums and target, return index of target or -1.",
                examples: &[Example { input: "nums = [-1, 0, 2, 4, 6, 8], target = 4", output: "3", explanation: "Found at index 3." }],
                constraints: &["1 <= nums.length <= 10000"], leetcode_url: "https://leetcode.com/problems/binary-search/",
                approaches: &[ApproachMeta { id: 0, name: "Binary Search Iterative", time_complexity: "O(log N)", space_complexity: "O(1)", rationale: "Halving the search space at each midpoint step guarantees logarithmic O(log N) runtime on sorted arrays.", description: "Midpoint bounds." }],
            }),
        Problem::Search2DMatrix => Some(ProblemDetails {
                id: 74, title: "Search a 2D Matrix", difficulty: Difficulty::Medium, category: Category::BinarySearch,
                statement: "Write an efficient algorithm that searches for a target value in an m x n integer matrix with sorted rows and columns.",
                examples: &[Example { input: "matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3", output: "true", explanation: "3 exists in row 0, col 1." }],
                constraints: &["m == matrix.length", "n == matrix[i].length", "1 <= m, n <= 100"], leetcode_url: "https://leetcode.com/problems/search-a-2d-matrix/",
                approaches: &[ApproachMeta { id: 0, name: "Binary Search Virtual 1D Array", time_complexity: "O(log(M*N))", space_complexity: "O(1)", rationale: "Treating the M x N matrix as a virtual 1D sorted array allows binary search in O(log(M*N)) time and O(1) space.", description: "Map mid index to matrix[mid / cols][mid % cols]." }],
            }),
        Problem::SearchRotatedArray => Some(ProblemDetails {
                id: 33, title: "Search in Rotated Sorted Array", difficulty: Difficulty::Medium, category: Category::BinarySearch,
                statement: "Given the array nums after the possible rotation and an integer target, return the index of target if it is in nums, or -1 if it is not in nums.",
                examples: &[Example { input: "nums = [4,5,6,7,0,1,2], target = 0", output: "4", explanation: "Binary search comparing mid with boundary values." }],
                constraints: &["1 <= nums.length <= 5000", "-10^4 <= nums[i] <= 10^4"], leetcode_url: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
                approaches: &[ApproachMeta { id: 0, name: "Rotated Binary Search", time_complexity: "O(log N)", space_complexity: "O(1)", rationale: "Identifying which half (left or right of mid) is sorted allows halving the search space in O(log N) time.", description: "Determine which half is sorted, check if target lies in that range." }],
            }),
        Problem::FindMinRotated => Some(ProblemDetails {
                id: 153, title: "Find Minimum in Rotated Sorted Array", difficulty: Difficulty::Medium, category: Category::BinarySearch,
                statement: "Suppose an array of length n sorted in ascending order is rotated between 1 and n times. Given the sorted rotated array nums of unique elements, return the minimum element of this array.",
                examples: &[Example { input: "nums = [3,4,5,1,2]", output: "1", explanation: "The original array was [1,2,3,4,5] rotated 3 times." }],
                constraints: &["1 <= n <= 5000", "-5000 <= nums[i] <= 5000"], leetcode_url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                approaches: &[ApproachMeta { id: 0, name: "Binary Search Right Boundary Comparison", time_complexity: "O(log N)", space_complexity: "O(1)", rationale: "Comparing nums[mid] to nums[right] determines whether the rotation pivot is in the left or right half in O(log N) time.", description: "Compare nums[mid] with nums[right] to halve search space." }],
            }),
        Problem::TimeKeyValueStore => Some(ProblemDetails {
                id: 981, title: "Time Based Key-Value Store", difficulty: Difficulty::Medium, category: Category::BinarySearch,
                statement: "Design a time-based key-value data structure that can store multiple values for the same key at different time stamps and retrieve the key's value at a certain timestamp.",
                examples: &[Example { input: "set(\"foo\", \"bar\", 1), get(\"foo\", 1), get(\"foo\", 3)", output: "\"bar\", \"bar\"", explanation: "Binary search list of (timestamp, value) pairs." }],
                constraints: &["1 <= key.length, value.length <= 100", "1 <= timestamp <= 10^7"], leetcode_url: "https://leetcode.com/problems/time-based-key-value-store/",
                approaches: &[ApproachMeta { id: 0, name: "HashMap + Binary Search Timestamps", time_complexity: "O(log N) get", space_complexity: "O(N)", rationale: "HashMap maps key to a vector of (timestamp, value) pairs; binary search finds upper bound timestamp in O(log N) time.", description: "HashMap maps key to sorted list of (time, val), binary search for upper bound." }],
            }),
        Problem::FindMedianSortedArrays => Some(ProblemDetails {
                id: 4, title: "Median of Two Sorted Arrays", difficulty: Difficulty::Hard, category: Category::BinarySearch,
                statement: "Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.",
                examples: &[Example { input: "nums1 = [1,3], nums2 = [2,4]", output: "2.5", explanation: "merged array = [1,2,3,4] and median is (2 + 3) / 2 = 2.5." }],
                constraints: &["nums1.length == m", "nums2.length == n", "0 <= m, n <= 1000"], leetcode_url: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
                approaches: &[ApproachMeta { id: 0, name: "Binary Search Partition on Smaller Array", time_complexity: "O(log(min(M, N)))", space_complexity: "O(1)", rationale: "Binary searching partition index on the smaller array balances left and right halves in O(log(min(M, N))) time.", description: "Binary search partition index i in A such that A[i-1] <= B[j] and B[j-1] <= A[i]." }],
            }),
        Problem::KokoEatingBananas => Some(ProblemDetails {
                id: 875, title: "Koko Eating Bananas", difficulty: Difficulty::Medium, category: Category::BinarySearch,
                statement: "Koko loves to eat bananas. There are n piles of bananas, the i-th pile has piles[i] bananas. The guards have gone and will come back in h hours. Koko can decide her banana-eating speed of k (bananas-per-hour). Each hour, she chooses some pile of bananas and eats k bananas from that pile. Return the minimum integer k such that she can eat all the bananas within h hours.",
                examples: &[Example { input: "piles = [3, 6, 7, 11], h = 8", output: "4", explanation: "At speed k = 4, total hours = 1 + 2 + 2 + 3 = 8 <= 8." }],
                constraints: &["1 <= piles.length <= 10^4", "piles.length <= h <= 10^9", "1 <= piles[i] <= 10^9"], leetcode_url: "https://leetcode.com/problems/koko-eating-bananas/",
                approaches: &[ApproachMeta { id: 0, name: "Binary Search on Eating Speed k", time_complexity: "O(N log(max(piles)))", space_complexity: "O(1)", rationale: "Binary search on speed k in range [1, max(piles)]. Calculate total hours needed for each candidate mid speed; if total_hours <= h, speed k works so we record it and search smaller speeds (r = mid - 1); otherwise we need a faster speed (l = mid + 1).", description: "Binary search eating speed k in range [1, max(piles)]." }],
            }),
        _ => None,
    }
}

pub fn get_code_lines(problem: Problem, approach_id: usize) -> Option<Vec<(usize, &'static str)>> {
    match (problem, approach_id) {
        (Problem::BinarySearch, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def search(self, nums: List[int], target: int) -> int:"),
            (3, "        l, r = 0, len(nums) - 1"),
            (4, "        while l <= r:"),
            (5, "            m = l + ((r - l) // 2)"),
            (6, "            if nums[m] > target:"),
            (7, "                r = m - 1"),
            (8, "            elif nums[m] < target:"),
            (9, "                l = m + 1"),
            (10, "            else:"),
            (11, "                return m"),
            (12, "        return -1"),
        ]),
        (Problem::Search2DMatrix, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def searchMatrix(self, matrix: List[List[int]], target: int) -> bool:"),
            (3, "        ROWS, COLS = len(matrix), len(matrix[0])"),
            (4, "        l, r = 0, ROWS * COLS - 1"),
            (5, "        while l <= r:"),
            (6, "            m = (l + r) // 2"),
            (7, "            row, col = m // COLS, m % COLS"),
            (8, "            if target > matrix[row][col]: l = m + 1"),
            (9, "            elif target < matrix[row][col]: r = m - 1"),
            (10, "            else: return True"),
            (11, "        return False"),
        ]),
        (Problem::SearchRotatedArray, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def search(self, nums: List[int], target: int) -> int:"),
            (3, "        l, r = 0, len(nums) - 1"),
            (4, "        while l <= r:"),
            (5, "            mid = (l + r) // 2"),
            (6, "            if target == nums[mid]: return mid"),
            (7, "            if nums[l] <= nums[mid]:"),
            (8, "                if nums[l] <= target < nums[mid]: r = mid - 1"),
            (9, "                else: l = mid + 1"),
            (10, "            else:"),
            (11, "                if nums[mid] < target <= nums[r]: l = mid + 1"),
            (12, "                else: r = mid - 1"),
            (13, "        return -1"),
        ]),
        (Problem::FindMinRotated, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def findMin(self, nums: List[int]) -> int:"),
            (3, "        l, r = 0, len(nums) - 1"),
            (4, "        while l < r:"),
            (5, "            mid = (l + r) // 2"),
            (6, "            if nums[mid] > nums[r]:"),
            (7, "                l = mid + 1"),
            (8, "            else:"),
            (9, "                r = mid"),
            (10, "        return nums[l]"),
        ]),
        (Problem::TimeKeyValueStore, _) => Some(vec![
            (1, "class TimeMap:"),
            (2, "    def __init__(self): self.store = {}"),
            (3, "    def set(self, key: str, value: str, timestamp: int) -> None:"),
            (4, "        if key not in self.store: self.store[key] = []"),
            (5, "        self.store[key].append([value, timestamp])"),
            (6, "    def get(self, key: str, timestamp: int) -> str:"),
            (7, "        res, values = \"\", self.store.get(key, [])"),
            (8, "        l, r = 0, len(values) - 1"),
            (9, "        while l <= r:"),
            (10, "            m = (l + r) // 2"),
            (11, "            if values[m][1] <= timestamp: res = values[m][0]; l = m + 1"),
            (12, "            else: r = m - 1"),
            (13, "        return res"),
        ]),
        (Problem::FindMedianSortedArrays, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def findMedianSortedArrays(self, nums1: List[int], nums2: List[int]) -> float:"),
            (3, "        A, B = nums1, nums2; total = len(A) + len(B); half = total // 2"),
            (4, "        if len(B) < len(A): A, B = B, A"),
            (5, "        l, r = 0, len(A) - 1"),
            (6, "        while True:"),
            (7, "            i = (l + r) // 2; j = half - i - 2"),
            (8, "            Aleft = A[i] if i >= 0 else float(\"-inf\")"),
            (9, "            Aright = A[i + 1] if (i + 1) < len(A) else float(\"inf\")"),
            (10, "            Bleft = B[j] if j >= 0 else float(\"-inf\")"),
            (11, "            Bright = B[j + 1] if (j + 1) < len(B) else float(\"inf\")"),
            (12, "            if Aleft <= Bright and Bleft <= Aright:"),
            (13, "                if total % 2: return min(Aright, Bright)"),
            (14, "                return (max(Aleft, Bleft) + min(Aright, Bright)) / 2"),
            (15, "            elif Aleft > Bright: r = i - 1"),
            (16, "            else: l = i + 1"),
        ]),
        (Problem::KokoEatingBananas, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def minEatingSpeed(self, piles: List[int], h: int) -> int:"),
            (3, "        l, r = 1, max(piles); res = r"),
            (4, "        while l <= r:"),
            (5, "            k = (l + r) // 2"),
            (6, "            hours = sum(math.ceil(p / k) for p in piles)"),
            (7, "            if hours <= h:"),
            (8, "                res = k"),
            (9, "                r = k - 1"),
            (10, "            else:"),
            (11, "                l = k + 1"),
            (12, "        return res"),
        ]),
        _ => None,
    }
}
