use crate::model::problem::{ApproachMeta, Example, Problem, ProblemDetails};
use crate::model::taxonomy::{Category, Difficulty};

pub fn get_details(problem: Problem) -> Option<ProblemDetails> {
    match problem {
        Problem::BestTimeStock => Some(ProblemDetails {
                id: 121, title: "Best Time to Buy and Sell Stock", difficulty: Difficulty::Easy, category: Category::SlidingWindow,
                statement: "Choose a single day to buy and a future day to sell to maximize profit.",
                examples: &[Example { input: "prices = [10, 1, 5, 6, 7, 1]", output: "6", explanation: "Buy at 1, sell at 7." }],
                constraints: &["1 <= prices.length <= 100"], leetcode_url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
                approaches: &[ApproachMeta { id: 0, name: "Two Pointers / Sliding Window", time_complexity: "O(N)", space_complexity: "O(1)", rationale: "Tracking the minimum buy price while scanning linear prices computes max profit in one O(N) pass with O(1) space.", description: "Min buy pointer, running max profit." }],
            }),
        Problem::LongestSubstring => Some(ProblemDetails {
                id: 3, title: "Longest Substring Without Repeating Characters", difficulty: Difficulty::Medium, category: Category::SlidingWindow,
                statement: "Given a string s, find the length of the longest substring without repeating characters.",
                examples: &[Example { input: "s = \"abcabcbb\"", output: "3", explanation: "The answer is \"abc\", with length 3." }],
                constraints: &["0 <= s.length <= 5*10^4"], leetcode_url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
                approaches: &[ApproachMeta { id: 0, name: "Sliding Window Set", time_complexity: "O(N)", space_complexity: "O(N)", rationale: "A sliding window HashSet expands right and shrinks left on duplicates, processing each character at most twice (O(N)).", description: "Expand right, shrink left on duplicate." }],
            }),
        Problem::CharacterReplacement => Some(ProblemDetails {
                id: 424, title: "Longest Repeating Character Replacement", difficulty: Difficulty::Medium, category: Category::SlidingWindow,
                statement: "You are given a string s and an integer k. You can choose any character of the string and change it to any other uppercase English character at most k times. Return the length of the longest substring containing the same letter.",
                examples: &[Example { input: "s = \"ABAB\", k = 2", output: "4", explanation: "Replace the two 'A's with 'B's or vice versa." }],
                constraints: &["1 <= s.length <= 10^5", "0 <= k <= s.length"], leetcode_url: "https://leetcode.com/problems/longest-repeating-character-replacement/",
                approaches: &[ApproachMeta { id: 0, name: "Sliding Window Frequency Map", time_complexity: "O(N)", space_complexity: "O(26)", rationale: "Maintaining max character frequency in sliding window shrinks left bound when (window_len - max_freq) > k in O(N) time.", description: "Maintain max frequency, shrink left when (window_len - max_freq) > k." }],
            }),
        Problem::PermutationInString => Some(ProblemDetails {
                id: 567, title: "Permutation in String", difficulty: Difficulty::Medium, category: Category::SlidingWindow,
                statement: "Given two strings s1 and s2, return true if s2 contains a permutation of s1, or false otherwise.",
                examples: &[Example { input: "s1 = \"ab\", s2 = \"eidbaooo\"", output: "true", explanation: "s2 contains one permutation of s1 (\"ba\")." }],
                constraints: &["1 <= s1.length, s2.length <= 10^4"], leetcode_url: "https://leetcode.com/problems/permutation-in-string/",
                approaches: &[ApproachMeta { id: 0, name: "Fixed Size Sliding Window Matches Count", time_complexity: "O(N)", space_complexity: "O(26)", rationale: "A fixed-size sliding window of length len(s1) matches character count frequencies in O(N) time and O(1) space.", description: "Slide window of size len(s1), track matching char counts." }],
            }),
        Problem::MinWindowSubstring => Some(ProblemDetails {
                id: 76, title: "Minimum Window Substring", difficulty: Difficulty::Hard, category: Category::SlidingWindow,
                statement: "Given two strings s and t of lengths m and n respectively, return the minimum window substring of s such that every character in t (including duplicates) is included in the window.",
                examples: &[Example { input: "s = \"ADOBECODEBANC\", t = \"ABC\"", output: "\"BANC\"", explanation: "The minimum window substring \"BANC\" includes 'A', 'B', and 'C' from string t." }],
                constraints: &["m == s.length", "n == t.length", "1 <= m, n <= 10^5"], leetcode_url: "https://leetcode.com/problems/minimum-window-substring/",
                approaches: &[ApproachMeta { id: 0, name: "Dynamic Sliding Window Have/Need Map", time_complexity: "O(N)", space_complexity: "O(M+N)", rationale: "A dynamic sliding window expands right to satisfy target character counts and shrinks left to find minimum length in O(N) time.", description: "Expand right until valid, then shrink left to minimize window." }],
            }),
        Problem::SlidingWindowMax => Some(ProblemDetails {
                id: 239, title: "Sliding Window Maximum", difficulty: Difficulty::Hard, category: Category::SlidingWindow,
                statement: "You are given an array of integers nums, there is a sliding window of size k which is moving from the very left of the array to the very right. Return the max sliding window.",
                examples: &[Example { input: "nums = [1,3,-1,-3,5,3,6,7], k = 3", output: "[3,3,5,5,6,7]", explanation: "Monotonic deque tracks sliding window maximum in O(N)." }],
                constraints: &["1 <= nums.length <= 10^5", "1 <= k <= nums.length"], leetcode_url: "https://leetcode.com/problems/sliding-window-maximum/",
                approaches: &[ApproachMeta { id: 0, name: "Monotonic Decreasing Deque", time_complexity: "O(N)", space_complexity: "O(k)", rationale: "A monotonic decreasing deque stores indices of potential max values, removing expired indices in O(N) time.", description: "Maintain deque of indices with strictly decreasing values." }],
            }),
        _ => None,
    }
}

pub fn get_code_lines(problem: Problem, approach_id: usize) -> Option<Vec<(usize, &'static str)>> {
    match (problem, approach_id) {
        (Problem::BestTimeStock, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def maxProfit(self, prices: List[int]) -> int:"),
            (3, "        l, r = 0, 1; maxP = 0"),
            (4, "        while r < len(prices):"),
            (5, "            if prices[l] < prices[r]:"),
            (6, "                profit = prices[r] - prices[l]"),
            (7, "                maxP = max(maxP, profit)"),
            (8, "            else:"),
            (9, "                # A lower price is a better buying opportunity"),
            (10, "                l = r"),
            (11, "            r += 1"),
            (12, "        return maxP"),
        ]),
        (Problem::LongestSubstring, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def lengthOfLongestSubstring(self, s: str) -> int:"),
            (3, "        charSet = set(); l = 0; res = 0"),
            (4, "        for r in range(len(s)):"),
            (5, "            while s[r] in charSet:"),
            (6, "                charSet.remove(s[l]); l += 1"),
            (7, "            charSet.add(s[r])"),
            (8, "            res = max(res, r - l + 1)"),
            (9, "        return res"),
        ]),
        (Problem::CharacterReplacement, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def characterReplacement(self, s: str, k: int) -> int:"),
            (3, "        count = {}; res = 0; l = 0; maxf = 0"),
            (4, "        for r in range(len(s)):"),
            (5, "            count[s[r]] = 1 + count.get(s[r], 0); maxf = max(maxf, count[s[r]])"),
            (6, "            while (r - l + 1) - maxf > k:"),
            (7, "                count[s[l]] -= 1; l += 1"),
            (8, "            res = max(res, r - l + 1)"),
            (9, "        return res"),
        ]),
        (Problem::PermutationInString, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def checkInclusion(self, s1: str, s2: str) -> bool:"),
            (3, "        if len(s1) > len(s2): return False"),
            (4, "        s1Count, s2Count = [0] * 26, [0] * 26"),
            (5, "        for i in range(len(s1)): s1Count[ord(s1[i]) - 97] += 1; s2Count[ord(s2[i]) - 97] += 1"),
            (6, "        matches = sum(1 for i in range(26) if s1Count[i] == s2Count[i])"),
            (7, "        l = 0"),
            (8, "        for r in range(len(s1), len(s2)):"),
            (9, "            if matches == 26: return True"),
            (10, "            index = ord(s2[r]) - 97; s2Count[index] += 1"),
            (11, "            if s1Count[index] == s2Count[index]: matches += 1"),
            (12, "            elif s1Count[index] + 1 == s2Count[index]: matches -= 1"),
            (13, "            index = ord(s2[l]) - 97; s2Count[index] -= 1"),
            (14, "            if s1Count[index] == s2Count[index]: matches += 1"),
            (15, "            elif s1Count[index] == s2Count[index] + 1: matches -= 1"),
            (16, "            l += 1"),
            (17, "        return matches == 26"),
        ]),
        (Problem::MinWindowSubstring, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def minWindow(self, s: str, t: str) -> str:"),
            (3, "        if not t: return \"\""),
            (4, "        countT, window = {}, {}"),
            (5, "        for c in t: countT[c] = 1 + countT.get(c, 0)"),
            (6, "        have, need = 0, len(countT); res, resLen = [-1, -1], float(\"infinity\"); l = 0"),
            (7, "        for r in range(len(s)):"),
            (8, "            c = s[r]; window[c] = 1 + window.get(c, 0)"),
            (9, "            if c in countT and window[c] == countT[c]: have += 1"),
            (10, "            while have == need:"),
            (11, "                if (r - l + 1) < resLen: res = [l, r]; resLen = r - l + 1"),
            (12, "                window[s[l]] -= 1"),
            (13, "                if s[l] in countT and window[s[l]] < countT[s[l]]: have -= 1"),
            (14, "                l += 1"),
            (15, "        l, r = res; return s[l : r + 1] if resLen != float(\"infinity\") else \"\""),
        ]),
        (Problem::SlidingWindowMax, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def maxSlidingWindow(self, nums: List[int], k: int) -> List[int]:"),
            (3, "        output = []; q = collections.deque(); l = r = 0"),
            (4, "        while r < len(nums):"),
            (5, "            while q and nums[q[-1]] < nums[r]: q.pop()"),
            (6, "            q.append(r)"),
            (7, "            if l > q[0]: q.popleft()"),
            (8, "            if (r + 1) >= k: output.append(nums[q[0]]); l += 1"),
            (9, "            r += 1"),
            (10, "        return output"),
        ]),
        _ => None,
    }
}
