use crate::model::problem::{ApproachMeta, Example, Problem, ProblemDetails};
use crate::model::taxonomy::{Category, Difficulty};

pub fn get_details(problem: Problem) -> Option<ProblemDetails> {
    match problem {
        Problem::ValidParentheses => Some(ProblemDetails {
                id: 20, title: "Valid Parentheses", difficulty: Difficulty::Easy, category: Category::Stack,
                statement: "Return true if the input bracket string is valid.",
                examples: &[Example { input: "s = \"([{}])\"", output: "true", explanation: "Matched brackets." }],
                constraints: &["1 <= s.length <= 1000"], leetcode_url: "https://leetcode.com/problems/valid-parentheses/",
                approaches: &[ApproachMeta { id: 0, name: "Stack Matching", time_complexity: "O(N)", space_complexity: "O(N)", rationale: "A LIFO stack matches closing brackets with the most recently opened bracket in O(N) time and O(N) memory.", description: "Push open, pop matching close." }],
            }),
        Problem::MinStack => Some(ProblemDetails {
                id: 155, title: "Min Stack", difficulty: Difficulty::Medium, category: Category::Stack,
                statement: "Design a stack that supports push, pop, top, and retrieving the minimum element in constant time O(1).",
                examples: &[Example { input: "push(-2), push(0), push(-3), getMin(), pop(), top(), getMin()", output: "getMin() = -3, top() = 0, getMin() = -2", explanation: "Min stack tracks minimum element at every push level." }],
                constraints: &["-2^31 <= val <= 2^31 - 1", "Methods pop, top and getMin will always be called on non-empty stacks"], leetcode_url: "https://leetcode.com/problems/min-stack/",
                approaches: &[ApproachMeta { id: 0, name: "Two Stacks (Value + MinStack)", time_complexity: "O(1)", space_complexity: "O(N)", rationale: "Storing running minimums alongside stack values guarantees O(1) constant time retrieval for min operations.", description: "Maintain parallel stack tracking minimums." }],
            }),
        Problem::EvalRPN => Some(ProblemDetails {
                id: 150, title: "Evaluate Reverse Polish Notation", difficulty: Difficulty::Medium, category: Category::Stack,
                statement: "Evaluate the value of an arithmetic expression in Reverse Polish Notation (postfix). Valid operators are +, -, *, and /.",
                examples: &[Example { input: "tokens = [\"2\", \"1\", \"+\", \"3\", \"*\"]", output: "9", explanation: "((2 + 1) * 3) = 9." }],
                constraints: &["1 <= tokens.length <= 10^4", "tokens[i] is an operator or integer in range [-200, 200]"], leetcode_url: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
                approaches: &[ApproachMeta { id: 0, name: "Stack Operand Evaluation", time_complexity: "O(N)", space_complexity: "O(N)", rationale: "Postfix evaluation using a LIFO stack processes operands and applies operators in linear O(N) time.", description: "Push numbers, pop 2 numbers on operator." }],
            }),
        Problem::GenerateParentheses => Some(ProblemDetails {
                id: 22, title: "Generate Parentheses", difficulty: Difficulty::Medium, category: Category::Stack,
                statement: "Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.",
                examples: &[Example { input: "n = 3", output: "[\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]", explanation: "All 5 valid combinations." }],
                constraints: &["1 <= n <= 8"], leetcode_url: "https://leetcode.com/problems/generate-parentheses/",
                approaches: &[ApproachMeta { id: 0, name: "Backtracking / Stack", time_complexity: "O(4^N / sqrt(N))", space_complexity: "O(N)", rationale: "Backtracking only branches when open_count < N or close_count < open_count, generating only valid combinations.", description: "Recursively build string adhering to open < n and close < open." }],
            }),
        Problem::DailyTemperatures => Some(ProblemDetails {
                id: 739, title: "Daily Temperatures", difficulty: Difficulty::Medium, category: Category::Stack,
                statement: "Given an array of integers temperatures represents the daily temperatures, return an array answer such that answer[i] is the number of days you have to wait after the i-th day to get a warmer temperature.",
                examples: &[Example { input: "temperatures = [73, 74, 75, 71, 69, 72, 76, 73]", output: "[1, 1, 4, 2, 1, 1, 0, 0]", explanation: "Monotonic stack tracking waiting days." }],
                constraints: &["1 <= temperatures.length <= 10^5", "30 <= temperatures[i] <= 100"], leetcode_url: "https://leetcode.com/problems/daily-temperatures/",
                approaches: &[ApproachMeta { id: 0, name: "Monotonic Decreasing Stack", time_complexity: "O(N)", space_complexity: "O(N)", rationale: "A monotonic decreasing stack stores indices waiting for warmer days, resolving each index in O(N) time.", description: "Maintain stack of indices in decreasing temperature order." }],
            }),
        Problem::CarFleet => Some(ProblemDetails {
                id: 853, title: "Car Fleet", difficulty: Difficulty::Medium, category: Category::Stack,
                statement: "There are n cars at given miles away from the starting mile 0, traveling to a destination target. Return the number of car fleets that will arrive at the destination.",
                examples: &[Example { input: "target = 12, position = [10,8,0,5,3], speed = [2,4,1,1,3]", output: "3", explanation: "Cars starting at 10 and 8 merge into 1 fleet, 5 and 3 merge into 1 fleet, 0 drives alone." }],
                constraints: &["n == position.length == speed.length", "1 <= n <= 10^5"], leetcode_url: "https://leetcode.com/problems/car-fleet/",
                approaches: &[ApproachMeta { id: 0, name: "Monotonic Time Stack (Position Order)", time_complexity: "O(N log N)", space_complexity: "O(N)", rationale: "Sorting cars by start position descending computes arrival times; if a car behind arrives earlier, it joins the fleet (O(N log N)).", description: "Sort by position desc, pop if car behind catches up." }],
            }),
        Problem::LargestRectangle => Some(ProblemDetails {
                id: 84, title: "Largest Rectangle in Histogram", difficulty: Difficulty::Hard, category: Category::Stack,
                statement: "Given an array of integers heights representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.",
                examples: &[Example { input: "heights = [2, 1, 5, 6, 2, 3]", output: "10", explanation: "The largest rectangle has area = 10 units (heights 5 and 6)." }],
                constraints: &["1 <= heights.length <= 10^5", "0 <= heights[i] <= 10^4"], leetcode_url: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
                approaches: &[ApproachMeta { id: 0, name: "Monotonic Increasing Stack", time_complexity: "O(N)", space_complexity: "O(N)", rationale: "A monotonic increasing stack of heights computes maximum rectangular area bounds upon popping in O(N) time.", description: "Maintain (index, height) pair stack, compute max area on pop." }],
            }),
        _ => None,
    }
}

pub fn get_code_lines(problem: Problem, approach_id: usize) -> Option<Vec<(usize, &'static str)>> {
    match (problem, approach_id) {
        (Problem::ValidParentheses, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def isValid(self, s: str) -> bool:"),
            (3, "        stack = []"),
            (4, "        closeToOpen = {\")\": \"(\", \"]\": \"[\", \"}\": \"{\"}"),
            (5, "        for c in s:"),
            (6, "            if c in closeToOpen:"),
            (7, "                if stack and stack[-1] == closeToOpen[c]: stack.pop()"),
            (8, "                else: return False"),
            (9, "            else: stack.append(c)"),
            (10, "        return True if not stack else False"),
        ]),
        (Problem::MinStack, _) => Some(vec![
            (1, "class MinStack:"),
            (2, "    def __init__(self):"),
            (3, "        self.stack = []"),
            (4, "        self.minStack = []"),
            (5, "    def push(self, val: int) -> None:"),
            (6, "        self.stack.append(val)"),
            (7, "        val = min(val, self.minStack[-1] if self.minStack else val)"),
            (8, "        self.minStack.append(val)"),
            (9, "    def pop(self) -> None:"),
            (10, "        self.stack.pop(); self.minStack.pop()"),
            (11, "    def top(self) -> int: return self.stack[-1]"),
            (12, "    def getMin(self) -> int: return self.minStack[-1]"),
        ]),
        (Problem::EvalRPN, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def evalRPN(self, tokens: List[str]) -> int:"),
            (3, "        stack = []"),
            (4, "        for c in tokens:"),
            (5, "            if c == '+': stack.append(stack.pop() + stack.pop())"),
            (6, "            elif c == '-': a, b = stack.pop(), stack.pop(); stack.append(b - a)"),
            (7, "            elif c == '*': stack.append(stack.pop() * stack.pop())"),
            (8, "            elif c == '/': a, b = stack.pop(), stack.pop(); stack.append(int(b / a))"),
            (9, "            else: stack.append(int(c))"),
            (10, "        return stack[0]"),
        ]),
        (Problem::GenerateParentheses, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def generateParenthesis(self, n: int) -> List[str]:"),
            (3, "        stack = []; res = []"),
            (4, "        def backtrack(openN, closedN):"),
            (5, "            if openN == closedN == n: res.append(\"\".join(stack)); return"),
            (6, "            if openN < n: stack.append(\"(\"); backtrack(openN + 1, closedN); stack.pop()"),
            (7, "            if closedN < openN: stack.append(\")\"); backtrack(openN, closedN + 1); stack.pop()"),
            (8, "        backtrack(0, 0); return res"),
        ]),
        (Problem::DailyTemperatures, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def dailyTemperatures(self, temperatures: List[int]) -> List[int]:"),
            (3, "        res = [0] * len(temperatures); stack = []"),
            (4, "        for i, t in enumerate(temperatures):"),
            (5, "            while stack and t > stack[-1][0]:"),
            (6, "                stackT, stackInd = stack.pop(); res[stackInd] = i - stackInd"),
            (7, "            stack.append((t, i))"),
            (8, "        return res"),
        ]),
        (Problem::CarFleet, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def carFleet(self, target: int, position: List[int], speed: List[int]) -> int:"),
            (3, "        pair = [(p, s) for p, s in zip(position, speed)]"),
            (4, "        pair.sort(reverse=True); stack = []"),
            (5, "        for p, s in pair:"),
            (6, "            stack.append((target - p) / s)"),
            (7, "            if len(stack) >= 2 and stack[-1] <= stack[-2]: stack.pop()"),
            (8, "        return len(stack)"),
        ]),
        (Problem::LargestRectangle, _) => Some(vec![
            (1, "class Solution:"),
            (2, "    def largestRectangleArea(self, heights: List[int]) -> int:"),
            (3, "        maxArea = 0; stack = []"),
            (4, "        for i, h in enumerate(heights):"),
            (5, "            start = i"),
            (6, "            while stack and stack[-1][1] > h:"),
            (7, "                index, height = stack.pop(); maxArea = max(maxArea, height * (i - index)); start = index"),
            (8, "            stack.append((start, h))"),
            (9, "        for i, h in stack: maxArea = max(maxArea, h * (len(heights) - i))"),
            (10, "        return maxArea"),
        ]),
        _ => None,
    }
}
