use super::taxonomy::*;

// ── Problem Statement & Example Data Structures ──

pub struct Example {
    pub input: &'static str,
    pub output: &'static str,
    pub explanation: &'static str,
}

pub struct ApproachMeta {
    pub id: usize,
    pub name: &'static str,
    pub time_complexity: &'static str,
    pub space_complexity: &'static str,
    pub rationale: &'static str,
    pub description: &'static str,
}

pub struct ProblemDetails {
    pub id: u32,
    pub title: &'static str,
    pub difficulty: Difficulty,
    pub category: Category,
    pub statement: &'static str,
    pub examples: &'static [Example],
    pub constraints: &'static [&'static str],
    pub leetcode_url: &'static str,
    pub approaches: &'static [ApproachMeta],
}

// ── Problem Enum (150 Problems) ──

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Problem {
    ContainsDuplicate,
    TwoSum,
    ValidAnagram,
    GroupAnagrams,
    TopKFrequent,
    ProductExceptSelf,
    EncodeDecode,
    ValidSudoku,
    LongestConsecutive,
    ValidPalindrome,
    BestTimeStock,
    ValidParentheses,
    BinarySearch,
    ReverseLinkedList,
    MergeTwoLists,
    LinkedListCycle,
    InvertTree,
    MaxDepthTree,
    DiameterTree,
    BalancedTree,
    SameTree,
    Subtree,
    LowestCommonAncestorBst,
    ClimbingStairs,
    MinCostStairs,
    KthLargestStream,
    LastStone,
    MeetingRooms,
    HappyNumber,
    PlusOne,
    SingleNumber,
    CountingBits,
    ReverseBits,
    MissingNumber,
    TwoSumII,
    ThreeSum,
    ContainerWater,
    TrappingRain,
    MinStack,
    EvalRPN,
    LongestSubstring,
    Search2DMatrix,
    HouseRobber,
    GenerateParentheses,
    DailyTemperatures,
    CarFleet,
    LargestRectangle,
    CharacterReplacement,
    PermutationInString,
    MinWindowSubstring,
    SlidingWindowMax,
    SearchRotatedArray,
    FindMinRotated,
    TimeKeyValueStore,
    FindMedianSortedArrays,
    KokoEatingBananas,
    ImplementTrie,
    WordDictionary,
    WordSearchII,
    Subsets,
    Permutations,
    KClosestPoints,
    TaskScheduler,
    FindMedianDataStream,
    CombinationSum,
    SubsetsII,
    CombinationSumII,
    WordSearch,
    NQueens,
    KthLargestArray,
    DesignTwitter,
    PalindromePartitioning,
    LetterCombinations,
    HouseRobberII,
    LongestPalindromicSubstring,
    PalindromicSubstrings,
    DecodeWays,
    CoinChange,
    MaxProductSubarray,
    WordBreak,
    LongestIncreasingSubsequence,
    PartitionEqualSubsetSum,
    Number1Bits,
    SumTwoIntegers,
    ReverseInteger,
    RotateImage,
    SpiralMatrix,
    SetMatrixZeroes,
    PowXN,
    MultiplyStrings,
    DetectSquares,
    MaximumSubarray,
    JumpGame,
    JumpGameII,
    GasStation,
    HandOfStraights,
    MergeTriplets,
    PartitionLabels,
    ValidParenthesisString,
    InsertInterval,
    MergeIntervals,
    NonOverlappingIntervals,
    MeetingRoomsII,
    MinIntervalQuery,
    NumberIslands,
    MaxAreaIsland,
    CloneGraph,
    WallsAndGates,
    RottingOranges,
    PacificAtlantic,
    SurroundedRegions,
    CourseSchedule,
    CourseScheduleII,
    GraphValidTree,
    ConnectedComponents,
    RedundantConnection,
    WordLadder,
    UniquePaths,
    LongestCommonSubsequence,
    BestTimeStockCooldown,
    CoinChangeII,
    TargetSum,
    InterleavingString,
    LongestIncreasingPath,
    DistinctSubsequences,
    EditDistance,
    BurstBalloons,
    RegularExpressionMatching,
    ReconstructItinerary,
    MinCostConnectPoints,
    NetworkDelayTime,
    SwimInRisingWater,
    AlienDictionary,
    CheapestFlights,
    ReorderList,
    RemoveNthNodeFromEnd,
    CopyListWithRandomPointer,
    AddTwoNumbers,
    FindDuplicateNumber,
    LruCache,
    MergeKSortedLists,
    ReverseNodesInKGroup,
    BinaryTreeLevelOrderTraversal,
    BinaryTreeRightSideView,
    CountGoodNodes,
    ValidateBinarySearchTree,
    KthSmallestElementBst,
    ConstructBinaryTreePreorderInorder,
    BinaryTreeMaxPathSum,
    SerializeDeserializeBinaryTree,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum AuditStatus {
    Audited,
    Unaudited,
}

impl Problem {
    pub fn audit_status(&self) -> AuditStatus {
        #[allow(clippy::match_single_binding)]
        match self {
            // Add future unaudited problems here:
            // Problem::NewProblem => AuditStatus::Unaudited,
            _ => AuditStatus::Audited,
        }
    }

    pub fn is_audited(&self) -> bool {
        self.audit_status() == AuditStatus::Audited
    }

    pub fn all() -> &'static [Problem] {
        &[
            Problem::ContainsDuplicate,
            Problem::TwoSum,
            Problem::ValidAnagram,
            Problem::GroupAnagrams,
            Problem::TopKFrequent,
            Problem::ProductExceptSelf,
            Problem::EncodeDecode,
            Problem::ValidSudoku,
            Problem::LongestConsecutive,
            Problem::ValidPalindrome,
            Problem::BestTimeStock,
            Problem::ValidParentheses,
            Problem::BinarySearch,
            Problem::ReverseLinkedList,
            Problem::MergeTwoLists,
            Problem::LinkedListCycle,
            Problem::InvertTree,
            Problem::MaxDepthTree,
            Problem::DiameterTree,
            Problem::BalancedTree,
            Problem::SameTree,
            Problem::Subtree,
            Problem::LowestCommonAncestorBst,
            Problem::ImplementTrie,
            Problem::WordDictionary,
            Problem::WordSearchII,
            Problem::Subsets,
            Problem::Permutations,
            Problem::KClosestPoints,
            Problem::TaskScheduler,
            Problem::FindMedianDataStream,
            Problem::CombinationSum,
            Problem::SubsetsII,
            Problem::CombinationSumII,
            Problem::WordSearch,
            Problem::NQueens,
            Problem::KthLargestArray,
            Problem::DesignTwitter,
            Problem::PalindromePartitioning,
            Problem::LetterCombinations,
            Problem::ClimbingStairs,
            Problem::MinCostStairs,
            Problem::HouseRobber,
            Problem::HouseRobberII,
            Problem::LongestPalindromicSubstring,
            Problem::PalindromicSubstrings,
            Problem::DecodeWays,
            Problem::CoinChange,
            Problem::MaxProductSubarray,
            Problem::WordBreak,
            Problem::LongestIncreasingSubsequence,
            Problem::PartitionEqualSubsetSum,
            Problem::KthLargestStream,
            Problem::LastStone,
            Problem::MeetingRooms,
            Problem::HappyNumber,
            Problem::PlusOne,
            Problem::SingleNumber,
            Problem::CountingBits,
            Problem::ReverseBits,
            Problem::MissingNumber,
            Problem::Number1Bits,
            Problem::SumTwoIntegers,
            Problem::ReverseInteger,
            Problem::RotateImage,
            Problem::SpiralMatrix,
            Problem::SetMatrixZeroes,
            Problem::PowXN,
            Problem::MultiplyStrings,
            Problem::DetectSquares,
            Problem::MaximumSubarray,
            Problem::JumpGame,
            Problem::JumpGameII,
            Problem::GasStation,
            Problem::HandOfStraights,
            Problem::MergeTriplets,
            Problem::PartitionLabels,
            Problem::ValidParenthesisString,
            Problem::InsertInterval,
            Problem::MergeIntervals,
            Problem::NonOverlappingIntervals,
            Problem::MeetingRoomsII,
            Problem::MinIntervalQuery,
            Problem::NumberIslands,
            Problem::MaxAreaIsland,
            Problem::CloneGraph,
            Problem::WallsAndGates,
            Problem::RottingOranges,
            Problem::PacificAtlantic,
            Problem::SurroundedRegions,
            Problem::CourseSchedule,
            Problem::CourseScheduleII,
            Problem::GraphValidTree,
            Problem::ConnectedComponents,
            Problem::RedundantConnection,
            Problem::WordLadder,
            Problem::UniquePaths,
            Problem::LongestCommonSubsequence,
            Problem::BestTimeStockCooldown,
            Problem::CoinChangeII,
            Problem::TargetSum,
            Problem::InterleavingString,
            Problem::LongestIncreasingPath,
            Problem::DistinctSubsequences,
            Problem::EditDistance,
            Problem::BurstBalloons,
            Problem::RegularExpressionMatching,
            Problem::ReconstructItinerary,
            Problem::MinCostConnectPoints,
            Problem::NetworkDelayTime,
            Problem::SwimInRisingWater,
            Problem::AlienDictionary,
            Problem::CheapestFlights,
            Problem::TwoSumII,
            Problem::ThreeSum,
            Problem::ContainerWater,
            Problem::TrappingRain,
            Problem::MinStack,
            Problem::EvalRPN,
            Problem::LongestSubstring,
            Problem::Search2DMatrix,
            Problem::GenerateParentheses,
            Problem::DailyTemperatures,
            Problem::CarFleet,
            Problem::LargestRectangle,
            Problem::CharacterReplacement,
            Problem::PermutationInString,
            Problem::MinWindowSubstring,
            Problem::SlidingWindowMax,
            Problem::SearchRotatedArray,
            Problem::FindMinRotated,
            Problem::TimeKeyValueStore,
            Problem::FindMedianSortedArrays,
            Problem::KokoEatingBananas,
            Problem::ReorderList,
            Problem::RemoveNthNodeFromEnd,
            Problem::CopyListWithRandomPointer,
            Problem::AddTwoNumbers,
            Problem::FindDuplicateNumber,
            Problem::LruCache,
            Problem::MergeKSortedLists,
            Problem::ReverseNodesInKGroup,
            Problem::BinaryTreeLevelOrderTraversal,
            Problem::BinaryTreeRightSideView,
            Problem::CountGoodNodes,
            Problem::ValidateBinarySearchTree,
            Problem::KthSmallestElementBst,
            Problem::ConstructBinaryTreePreorderInorder,
            Problem::BinaryTreeMaxPathSum,
            Problem::SerializeDeserializeBinaryTree,
        ]
    }

    pub fn id(&self) -> u32 {
        self.details().id
    }

    pub fn title(&self) -> &'static str {
        self.details().title
    }

    pub fn difficulty(&self) -> Difficulty {
        self.details().difficulty
    }

    pub fn category(&self) -> Category {
        self.details().category
    }

    pub fn formula(&self) -> Option<&'static str> {
        match self {
            Problem::ContainsDuplicate => Some("if n ∈ seen ➔ duplicate found"),
            Problem::TwoSum => Some("diff = target - num  ➔  map[diff]"),
            Problem::ValidAnagram => Some("count_S[char] == count_T[char]"),
            Problem::GroupAnagrams => Some("key = tuple(count_26_chars)"),
            Problem::TopKFrequent => Some("freq[num]++ ➔ bucket[cnt].append(num)"),
            Problem::ProductExceptSelf => Some("out[i] = prefix[i-1] × suffix[i+1]"),
            Problem::EncodeDecode => Some("encoded = str.len() + '#' + str"),
            Problem::ValidSudoku => Some("val ∉ row[r] ∩ col[c] ∩ box[r//3, c//3]"),
            Problem::LongestConsecutive => Some("if (num - 1) ∉ set ➔ streak start"),
            Problem::ValidPalindrome => Some("s[left].lower() == s[right].lower()"),
            Problem::BestTimeStock => Some("profit = max(0, prices[r] - prices[l])"),
            Problem::ValidParentheses => Some("open ➔ push(c), close ➔ pop() == match(c)"),
            Problem::BinarySearch => Some("mid = left + (right - left) // 2"),
            Problem::ReverseLinkedList => Some("curr.next = prev; prev = curr; curr = nxt"),
            Problem::MergeTwoLists => Some("tail.next = min(l1.val, l2.val)"),
            Problem::LinkedListCycle => Some("slow = slow.next; fast = fast.next.next"),
            Problem::InvertTree => Some("swap(root.left, root.right)"),
            Problem::MaxDepthTree => Some("depth = 1 + max(depth(L), depth(R))"),
            Problem::DiameterTree => Some("diameter = max(d, height(L) + height(R))"),
            Problem::BalancedTree => Some("abs(height(L) - height(R)) ≤ 1"),
            Problem::SameTree => Some("p.val == q.val ∧ same(p.L, q.L) ∧ same(p.R, q.R)"),
            Problem::Subtree => {
                Some("isSameTree(root, subRoot) ∨ isSubtree(root.L) ∨ isSubtree(root.R)")
            }
            Problem::ClimbingStairs => Some("dp[i] = dp[i-1] + dp[i-2]"),
            Problem::MinCostStairs => Some("dp[i] = cost[i] + min(dp[i+1], dp[i+2])"),
            Problem::KthLargestStream => Some("heapq.heappush(val); if len > k ➔ pop()"),
            Problem::LastStone => Some("stone_1 - stone_2 ➔ max_heap"),
            Problem::MeetingRooms => Some("interval[i].start < interval[i-1].end"),
            Problem::HappyNumber => Some("n = ∑(digit²)  ➔  detect cycle in HashSet"),
            Problem::PlusOne => Some("digits[i] = (digits[i] + 1) % 10"),
            Problem::SingleNumber => Some("a ⊕ a = 0  ➔  res ^= n"),
            Problem::Number1Bits => Some("n = n & (n - 1)  ➔  clears lowest set bit"),
            Problem::CountingBits => Some("dp[i] = 1 + dp[i - offset]"),
            Problem::ReverseBits => Some("bit = (n >> i) & 1  ➔  res |= bit << (31 - i)"),
            Problem::MissingNumber => Some("∑(0..n) - ∑(nums)  ➔  res ^= i ⊕ nums[i]"),
            Problem::TwoSumII => Some("sum = nums[l] + nums[r]  ➔  adjust l, r"),
            Problem::ThreeSum => Some("a + nums[l] + nums[r] == 0"),
            Problem::ContainerWater => Some("area = (r - l) × min(h[l], h[r])"),
            Problem::TrappingRain => Some("water[i] = min(max_L, max_R) - height[i]"),
            Problem::MinStack => Some("min_stack.push(min(val, min_stack[-1]))"),
            Problem::EvalRPN => Some("b = pop(), a = pop() ➔ push(a op b)"),
            Problem::LongestSubstring => Some("while s[r] ∈ set ➔ set.remove(s[l]); l++"),
            Problem::Search2DMatrix => Some("val = matrix[m // COLS][m % COLS]"),
            Problem::HouseRobber => Some("rob[i] = max(rob[i-1], rob[i-2] + nums[i])"),
            Problem::LowestCommonAncestorBst => {
                Some("p, q < root: search left; p, q > root: search right")
            }
            Problem::ValidateBinarySearchTree => Some("lower < node.val < upper"),
            Problem::GenerateParentheses => Some("open < n ➔ '(', closed < open ➔ ')'"),
            Problem::DailyTemperatures => Some("while t > stack[-1].val ➔ pop() & dist = i - idx"),
            Problem::CarFleet => Some("time = (target - p) / s; if t ≤ prev ➔ fleet merge"),
            Problem::LargestRectangle => Some("area = height × (i - start_index)"),
            Problem::CharacterReplacement => Some("window_len - max_freq ≤ k"),
            Problem::PermutationInString => Some("s1_count == s2_window_count"),
            Problem::MinWindowSubstring => Some("have == need ➔ shrink left window"),
            Problem::SlidingWindowMax => Some("deque monotonic decreasing indices"),
            Problem::SearchRotatedArray => Some("if nums[l] ≤ nums[m] ➔ left half sorted"),
            Problem::FindMinRotated => Some("if nums[m] > nums[r] ➔ min in right half"),
            Problem::TimeKeyValueStore => Some("binary search timestamp in key values"),
            Problem::FindMedianSortedArrays => Some("Aleft ≤ Bright ∧ Bleft ≤ Aright"),
            Problem::KokoEatingBananas => Some("hours <= h ➔ r = k - 1 else l = k + 1"),
            Problem::RotateImage => Some("transpose(matrix) ➔ reverse_rows(matrix)"),
            Problem::SpiralMatrix => Some("traverse(right, down, left, up) ➔ shrink bounds"),
            Problem::SetMatrixZeroes => Some("if cell == 0 ➔ mark row_flag[r] & col_flag[c]"),
            Problem::PowXN => Some("if N is odd ➔ res *= x; x *= x; N //= 2"),
            Problem::MultiplyStrings => Some("pos[i + j + 1] += d1 × d2 ➔ handle carry"),
            Problem::DetectSquares => Some("count += freq[p1] × freq[p2] × freq[p3]"),
            Problem::MaximumSubarray => Some("cur_sum = max(n, cur_sum + n)"),
            Problem::JumpGame => Some("max_reach = max(max_reach, i + nums[i])"),
            Problem::JumpGameII => Some("farthest = max(farthest, i + nums[i])"),
            Problem::GasStation => Some("total_tank += gas[i] - cost[i]"),
            Problem::CourseSchedule => Some("topological sort ➔ in_degree == 0"),
            Problem::UniquePaths => Some("dp[r][c] = dp[r+1][c] + dp[r][c+1]"),
            Problem::LongestCommonSubsequence => Some("if s1[i] == s2[j] ➔ 1 + dp[i+1][j+1]"),
            Problem::CoinChange => Some("dp[a] = min(dp[a], 1 + dp[a - coin])"),
            Problem::LongestIncreasingSubsequence => {
                Some("if nums[j] < nums[i] ➔ dp[i] = max(1 + dp[j])")
            }
            _ => None,
        }
    }

    pub fn details(&self) -> ProblemDetails {
        crate::model::problems::get_problem_details(*self)
    }
}

// ── Approach-Specific Code Lines Providers ──

pub fn approach_code_lines(problem: Problem, approach_id: usize) -> Vec<(usize, &'static str)> {
    crate::model::problems::get_problem_code_lines(problem, approach_id)
}
