use std::collections::{BTreeMap, BTreeSet};
use eframe::egui::Color32;

// ── Themes & Accessibility ──

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Theme {
    DarkVSCode,
    DarkCyber,
    LightClean,
}

impl Theme {
    pub fn label(&self) -> &'static str {
        match self {
            Theme::DarkVSCode => "VS Code Dark",
            Theme::DarkCyber => "Cyber Navy (Dark)",
            Theme::LightClean => "Clean Light",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ColorblindMode {
    Off,
    RedGreenSafe,
    HighContrast,
}

impl ColorblindMode {
    pub fn label(&self) -> &'static str {
        match self {
            ColorblindMode::Off => "Off (Standard)",
            ColorblindMode::RedGreenSafe => "Protan / Deuteran (Blue-Orange)",
            ColorblindMode::HighContrast => "High Contrast B&W",
        }
    }
}

#[derive(Debug, Clone)]
pub struct ThemePalette {
    pub bg_dark: Color32,
    pub sidebar_bg: Color32,
    pub step_box_bg: Color32,
    pub cell_bg: Color32,
    pub cell_border: Color32,
    pub text_primary: Color32,
    pub text_muted: Color32,
    pub text_dim: Color32,
    pub cyan: Color32,
    pub purple: Color32,
    pub emerald: Color32,
    pub emerald_text: Color32,
    pub amber: Color32,
    pub pink: Color32,
    pub red: Color32,
    pub code_active_bg: Color32,
}

impl Theme {
    pub fn palette(&self, cb: ColorblindMode) -> ThemePalette {
        let (base_emerald, base_emerald_text, base_red) = match cb {
            ColorblindMode::Off => (
                Color32::from_rgb(16, 185, 129),
                Color32::from_rgb(52, 211, 153),
                Color32::from_rgb(244, 63, 94),
            ),
            ColorblindMode::RedGreenSafe => (
                Color32::from_rgb(37, 99, 235),
                Color32::from_rgb(96, 165, 250),
                Color32::from_rgb(234, 88, 12),
            ),
            ColorblindMode::HighContrast => (
                Color32::from_rgb(255, 255, 255),
                Color32::from_rgb(255, 255, 255),
                Color32::from_rgb(255, 255, 0),
            ),
        };

        match self {
            Theme::DarkVSCode => ThemePalette {
                bg_dark: Color32::from_rgb(24, 24, 24),
                sidebar_bg: Color32::from_rgb(30, 30, 30),
                step_box_bg: Color32::from_rgb(37, 37, 38),
                cell_bg: Color32::from_rgb(45, 45, 48),
                cell_border: Color32::from_rgb(60, 60, 60),
                text_primary: Color32::from_rgb(220, 220, 220),
                text_muted: Color32::from_rgb(160, 160, 160),
                text_dim: Color32::from_rgb(110, 110, 110),
                cyan: Color32::from_rgb(86, 156, 214),
                purple: Color32::from_rgb(197, 134, 192),
                emerald: base_emerald,
                emerald_text: base_emerald_text,
                amber: Color32::from_rgb(206, 145, 120),
                pink: Color32::from_rgb(220, 100, 170),
                red: base_red,
                code_active_bg: Color32::from_rgb(9, 71, 113),
            },
            Theme::DarkCyber => ThemePalette {
                bg_dark: Color32::from_rgb(11, 15, 25),
                sidebar_bg: Color32::from_rgb(15, 23, 42),
                step_box_bg: Color32::from_rgb(30, 41, 59),
                cell_bg: Color32::from_rgb(30, 41, 59),
                cell_border: Color32::from_rgb(51, 65, 85),
                text_primary: Color32::from_rgb(248, 250, 252),
                text_muted: Color32::from_rgb(156, 163, 175),
                text_dim: Color32::from_rgb(100, 116, 139),
                cyan: Color32::from_rgb(56, 189, 248),
                purple: Color32::from_rgb(168, 85, 247),
                emerald: base_emerald,
                emerald_text: base_emerald_text,
                amber: Color32::from_rgb(245, 158, 11),
                pink: Color32::from_rgb(236, 72, 153),
                red: base_red,
                code_active_bg: Color32::from_rgb(14, 116, 144),
            },
            Theme::LightClean => ThemePalette {
                bg_dark: Color32::from_rgb(248, 250, 252),
                sidebar_bg: Color32::from_rgb(255, 255, 255),
                step_box_bg: Color32::from_rgb(241, 245, 249),
                cell_bg: Color32::from_rgb(241, 245, 249),
                cell_border: Color32::from_rgb(203, 213, 225),
                text_primary: Color32::from_rgb(15, 23, 42),
                text_muted: Color32::from_rgb(71, 85, 105),
                text_dim: Color32::from_rgb(148, 163, 184),
                cyan: Color32::from_rgb(2, 132, 199),
                purple: Color32::from_rgb(147, 51, 234),
                emerald: base_emerald,
                emerald_text: if cb == ColorblindMode::Off { Color32::from_rgb(5, 150, 105) } else { base_emerald_text },
                amber: Color32::from_rgb(217, 119, 6),
                pink: Color32::from_rgb(219, 39, 119),
                red: base_red,
                code_active_bg: Color32::from_rgb(186, 230, 253),
            },
        }
    }
}

// ── Difficulty Level ──

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Difficulty {
    Easy,
    Medium,
    Hard,
}

impl Difficulty {
    pub fn label(&self) -> &'static str {
        match self {
            Difficulty::Easy => "Easy",
            Difficulty::Medium => "Medium",
            Difficulty::Hard => "Hard",
        }
    }
}

// ── Roadmap Categories (NeetCode 150 Hierarchy) ──

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Category {
    ArraysAndHashing,
    TwoPointers,
    Stack,
    BinarySearch,
    SlidingWindow,
    LinkedList,
    Trees,
    Tries,
    Backtracking,
    HeapPriorityQueue,
    Graphs,
    OneDDp,
    Intervals,
    Greedy,
    AdvancedGraphs,
    TwoDDp,
    BitManipulation,
    MathAndGeometry,
}

impl Category {
    pub fn name(&self) -> &'static str {
        match self {
            Category::ArraysAndHashing => "Arrays & Hashing",
            Category::TwoPointers => "Two Pointers",
            Category::Stack => "Stack",
            Category::BinarySearch => "Binary Search",
            Category::SlidingWindow => "Sliding Window",
            Category::LinkedList => "Linked List",
            Category::Trees => "Trees",
            Category::Tries => "Tries",
            Category::Backtracking => "Backtracking",
            Category::HeapPriorityQueue => "Heap / Priority Queue",
            Category::Graphs => "Graphs",
            Category::OneDDp => "1-D DP",
            Category::Intervals => "Intervals",
            Category::Greedy => "Greedy",
            Category::AdvancedGraphs => "Advanced Graphs",
            Category::TwoDDp => "2-D DP",
            Category::BitManipulation => "Bit Manipulation",
            Category::MathAndGeometry => "Math & Geometry",
        }
    }

    pub fn all() -> &'static [Category] {
        &[
            Category::ArraysAndHashing,
            Category::TwoPointers,
            Category::Stack,
            Category::BinarySearch,
            Category::SlidingWindow,
            Category::LinkedList,
            Category::Trees,
            Category::Tries,
            Category::Backtracking,
            Category::HeapPriorityQueue,
            Category::Graphs,
            Category::OneDDp,
            Category::Intervals,
            Category::Greedy,
            Category::AdvancedGraphs,
            Category::TwoDDp,
            Category::BitManipulation,
            Category::MathAndGeometry,
        ]
    }
}

// ── Problem Statement & Example Data Structures ──

pub struct Example {
    pub input: &'static str,
    pub output: &'static str,
    pub explanation: &'static str,
}

pub struct ApproachMeta {
    pub id: usize,
    pub name: &'static str,
    pub time_complexity: &'static str,
    pub space_complexity: &'static str,
    pub description: &'static str,
}

pub struct ProblemDetails {
    pub id: u32,
    pub title: &'static str,
    pub difficulty: Difficulty,
    pub category: Category,
    pub statement: &'static str,
    pub examples: &'static [Example],
    pub constraints: &'static [&'static str],
    pub leetcode_url: &'static str,
    pub approaches: &'static [ApproachMeta],
}

// ── Problem Enum (34 Problems) ──

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Problem {
    ContainsDuplicate,
    TwoSum,
    ValidAnagram,
    GroupAnagrams,
    TopKFrequent,
    ProductExceptSelf,
    EncodeDecode,
    ValidSudoku,
    LongestConsecutive,
    ValidPalindrome,
    BestTimeStock,
    ValidParentheses,
    BinarySearch,
    ReverseLinkedList,
    MergeTwoLists,
    LinkedListCycle,
    InvertTree,
    MaxDepthTree,
    DiameterTree,
    BalancedTree,
    SameTree,
    Subtree,
    ClimbingStairs,
    MinCostStairs,
    KthLargestStream,
    LastStone,
    MeetingRooms,
    HappyNumber,
    PlusOne,
    SingleNumber,
    CountBits,
    CountingBits,
    ReverseBits,
    MissingNumber,
    TwoSumII,
    ThreeSum,
    ContainerWater,
    TrappingRain,
    MinStack,
    EvalRPN,
    LongestSubstring,
    Search2DMatrix,
    HouseRobber,
    GenerateParentheses,
    DailyTemperatures,
    CarFleet,
    LargestRectangle,
    CharacterReplacement,
    PermutationInString,
    MinWindowSubstring,
    SlidingWindowMax,
}

impl Problem {
    pub fn all() -> &'static [Problem] {
        &[
            Problem::ContainsDuplicate,
            Problem::TwoSum,
            Problem::ValidAnagram,
            Problem::GroupAnagrams,
            Problem::TopKFrequent,
            Problem::ProductExceptSelf,
            Problem::EncodeDecode,
            Problem::ValidSudoku,
            Problem::LongestConsecutive,
            Problem::ValidPalindrome,
            Problem::BestTimeStock,
            Problem::ValidParentheses,
            Problem::BinarySearch,
            Problem::ReverseLinkedList,
            Problem::MergeTwoLists,
            Problem::LinkedListCycle,
            Problem::InvertTree,
            Problem::MaxDepthTree,
            Problem::DiameterTree,
            Problem::BalancedTree,
            Problem::SameTree,
            Problem::Subtree,
            Problem::ClimbingStairs,
            Problem::MinCostStairs,
            Problem::KthLargestStream,
            Problem::LastStone,
            Problem::MeetingRooms,
            Problem::HappyNumber,
            Problem::PlusOne,
            Problem::SingleNumber,
            Problem::CountBits,
            Problem::CountingBits,
            Problem::ReverseBits,
            Problem::MissingNumber,
            Problem::TwoSumII,
            Problem::ThreeSum,
            Problem::ContainerWater,
            Problem::TrappingRain,
            Problem::MinStack,
            Problem::EvalRPN,
            Problem::LongestSubstring,
            Problem::Search2DMatrix,
            Problem::HouseRobber,
            Problem::GenerateParentheses,
            Problem::DailyTemperatures,
            Problem::CarFleet,
            Problem::LargestRectangle,
            Problem::CharacterReplacement,
            Problem::PermutationInString,
            Problem::MinWindowSubstring,
            Problem::SlidingWindowMax,
        ]
    }

    pub fn id(&self) -> u32 {
        self.details().id
    }

    pub fn title(&self) -> &'static str {
        self.details().title
    }

    pub fn difficulty(&self) -> Difficulty {
        self.details().difficulty
    }

    pub fn category(&self) -> Category {
        self.details().category
    }

    pub fn details(&self) -> ProblemDetails {
        match self {
            Problem::ContainsDuplicate => ProblemDetails {
                id: 217, title: "Contains Duplicate", difficulty: Difficulty::Easy, category: Category::ArraysAndHashing,
                statement: "Given an integer array nums, return true if any value appears at least twice in the array.",
                examples: &[Example { input: "nums = [1, 2, 3, 1]", output: "true", explanation: "Digit 1 appears twice." }],
                constraints: &["1 <= nums.length <= 10^5"], leetcode_url: "https://leetcode.com/problems/contains-duplicate/",
                approaches: &[ApproachMeta { id: 0, name: "Hash Set Lookup", time_complexity: "O(N)", space_complexity: "O(N)", description: "Insert into set, return true on collision." }],
            },
            Problem::TwoSum => ProblemDetails {
                id: 1, title: "Two Sum", difficulty: Difficulty::Easy, category: Category::ArraysAndHashing,
                statement: "Given an array of integers nums and a target, return indices of the two numbers that add up to target.",
                examples: &[Example { input: "nums = [2, 7, 11, 15], target = 9", output: "[0, 1]", explanation: "nums[0] + nums[1] == 9" }],
                constraints: &["2 <= nums.length <= 10^4"], leetcode_url: "https://leetcode.com/problems/two-sum/",
                approaches: &[ApproachMeta { id: 0, name: "Hash Map (One Pass)", time_complexity: "O(N)", space_complexity: "O(N)", description: "Use hash map complement lookup." }],
            },
            Problem::ValidAnagram => ProblemDetails {
                id: 242, title: "Valid Anagram", difficulty: Difficulty::Easy, category: Category::ArraysAndHashing,
                statement: "Given two strings s and t, return true if t is an anagram of s.",
                examples: &[Example { input: "s = \"anagram\", t = \"nagaram\"", output: "true", explanation: "Frequencies match." }],
                constraints: &["1 <= s.length <= 5*10^4"], leetcode_url: "https://leetcode.com/problems/valid-anagram/",
                approaches: &[ApproachMeta { id: 0, name: "Frequency Counter Array", time_complexity: "O(N)", space_complexity: "O(1)", description: "Count char frequencies." }],
            },
            Problem::GroupAnagrams => ProblemDetails {
                id: 49, title: "Group Anagrams", difficulty: Difficulty::Medium, category: Category::ArraysAndHashing,
                statement: "Given an array of strings strs, group the anagrams together.",
                examples: &[Example { input: "strs = [\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]", output: "[[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]", explanation: "Anagrams grouped by key." }],
                constraints: &["1 <= strs.length <= 10^4"], leetcode_url: "https://leetcode.com/problems/group-anagrams/",
                approaches: &[ApproachMeta { id: 0, name: "Char Frequency Tuple Map", time_complexity: "O(N * K)", space_complexity: "O(N * K)", description: "Tuple key map." }],
            },
            Problem::TopKFrequent => ProblemDetails {
                id: 347, title: "Top K Frequent Elements", difficulty: Difficulty::Medium, category: Category::ArraysAndHashing,
                statement: "Given an integer array nums and integer k, return the k most frequent elements.",
                examples: &[Example { input: "nums = [1,1,1,2,2,3], k = 2", output: "[1, 2]", explanation: "1 appears 3x, 2 appears 2x." }],
                constraints: &["1 <= nums.length <= 10^5"], leetcode_url: "https://leetcode.com/problems/top-k-frequent-elements/",
                approaches: &[ApproachMeta { id: 0, name: "Bucket Sort", time_complexity: "O(N)", space_complexity: "O(N)", description: "Frequency buckets." }],
            },
            Problem::ProductExceptSelf => ProblemDetails {
                id: 238, title: "Product of Array Except Self", difficulty: Difficulty::Medium, category: Category::ArraysAndHashing,
                statement: "Return an array output where output[i] is the product of all elements except nums[i].",
                examples: &[Example { input: "nums = [1, 2, 4, 6]", output: "[48, 24, 12, 8]", explanation: "Prefix/suffix passes." }],
                constraints: &["2 <= nums.length <= 1000"], leetcode_url: "https://leetcode.com/problems/product-of-array-except-self/",
                approaches: &[ApproachMeta { id: 0, name: "Prefix & Suffix Pass", time_complexity: "O(N)", space_complexity: "O(1)", description: "Running prefix & suffix." }],
            },
            Problem::EncodeDecode => ProblemDetails {
                id: 271, title: "Encode and Decode Strings", difficulty: Difficulty::Medium, category: Category::ArraysAndHashing,
                statement: "Design an algorithm to encode a list of strings to a string and decode it back.",
                examples: &[Example { input: "strs = [\"Hello\",\"World\"]", output: "[\"Hello\",\"World\"]", explanation: "Encoded into 5#Hello5#World." }],
                constraints: &["0 <= strs.length < 100"], leetcode_url: "https://leetcode.com/problems/encode-and-decode-strings/",
                approaches: &[ApproachMeta { id: 0, name: "Length Prefix (# Protocol)", time_complexity: "O(N)", space_complexity: "O(N)", description: "Len#str encoding." }],
            },
            Problem::ValidSudoku => ProblemDetails {
                id: 36, title: "Valid Sudoku", difficulty: Difficulty::Medium, category: Category::ArraysAndHashing,
                statement: "Determine if a 9x9 Sudoku board is valid (rows, cols, 3x3 boxes).",
                examples: &[Example { input: "board = [[1, 2, ...]]", output: "true", explanation: "No duplicates." }],
                constraints: &["board.length == 9"], leetcode_url: "https://leetcode.com/problems/valid-sudoku/",
                approaches: &[ApproachMeta { id: 0, name: "HashSet Validation", time_complexity: "O(1)", space_complexity: "O(1)", description: "Scan rows, cols, 3x3 boxes." }],
            },
            Problem::LongestConsecutive => ProblemDetails {
                id: 128, title: "Longest Consecutive Sequence", difficulty: Difficulty::Medium, category: Category::ArraysAndHashing,
                statement: "Return the length of the longest consecutive elements sequence.",
                examples: &[Example { input: "nums = [2, 20, 4, 10, 3, 4, 5]", output: "4", explanation: "Sequence [2, 3, 4, 5]." }],
                constraints: &["0 <= nums.length <= 1000"], leetcode_url: "https://leetcode.com/problems/longest-consecutive-sequence/",
                approaches: &[ApproachMeta { id: 0, name: "HashSet Sequence Start Expansion", time_complexity: "O(N)", space_complexity: "O(N)", description: "Expand from streak starts." }],
            },
            Problem::ValidPalindrome => ProblemDetails {
                id: 125, title: "Valid Palindrome", difficulty: Difficulty::Easy, category: Category::TwoPointers,
                statement: "Given a string s, return true if it is a palindrome.",
                examples: &[Example { input: "s = \"Was it a car or a cat I saw?\"", output: "true", explanation: "Alphanumeric filter palindrome." }],
                constraints: &["1 <= s.length <= 1000"], leetcode_url: "https://leetcode.com/problems/valid-palindrome/",
                approaches: &[ApproachMeta { id: 0, name: "Two Pointers In-Place", time_complexity: "O(N)", space_complexity: "O(1)", description: "Left and right pointers." }],
            },
            Problem::BestTimeStock => ProblemDetails {
                id: 121, title: "Best Time to Buy and Sell Stock", difficulty: Difficulty::Easy, category: Category::SlidingWindow,
                statement: "Choose a single day to buy and a future day to sell to maximize profit.",
                examples: &[Example { input: "prices = [10, 1, 5, 6, 7, 1]", output: "6", explanation: "Buy at 1, sell at 7." }],
                constraints: &["1 <= prices.length <= 100"], leetcode_url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
                approaches: &[ApproachMeta { id: 0, name: "Two Pointers / Sliding Window", time_complexity: "O(N)", space_complexity: "O(1)", description: "Min buy pointer, running max profit." }],
            },
            Problem::ValidParentheses => ProblemDetails {
                id: 20, title: "Valid Parentheses", difficulty: Difficulty::Easy, category: Category::Stack,
                statement: "Return true if the input bracket string is valid.",
                examples: &[Example { input: "s = \"([{}])\"", output: "true", explanation: "Matched brackets." }],
                constraints: &["1 <= s.length <= 1000"], leetcode_url: "https://leetcode.com/problems/valid-parentheses/",
                approaches: &[ApproachMeta { id: 0, name: "Stack Matching", time_complexity: "O(N)", space_complexity: "O(N)", description: "Push open, pop matching close." }],
            },
            Problem::BinarySearch => ProblemDetails {
                id: 704, title: "Binary Search", difficulty: Difficulty::Easy, category: Category::BinarySearch,
                statement: "Given sorted array nums and target, return index of target or -1.",
                examples: &[Example { input: "nums = [-1, 0, 2, 4, 6, 8], target = 4", output: "3", explanation: "Found at index 3." }],
                constraints: &["1 <= nums.length <= 10000"], leetcode_url: "https://leetcode.com/problems/binary-search/",
                approaches: &[ApproachMeta { id: 0, name: "Binary Search Iterative", time_complexity: "O(log N)", space_complexity: "O(1)", description: "Midpoint bounds." }],
            },
            Problem::ReverseLinkedList => ProblemDetails {
                id: 206, title: "Reverse Linked List", difficulty: Difficulty::Easy, category: Category::LinkedList,
                statement: "Reverse a singly linked list.",
                examples: &[Example { input: "head = [0, 1, 2, 3]", output: "[3, 2, 1, 0]", explanation: "Next pointers flipped." }],
                constraints: &["0 <= length <= 1000"], leetcode_url: "https://leetcode.com/problems/reverse-linked-list/",
                approaches: &[ApproachMeta { id: 0, name: "Iterative Pointers (prev, curr)", time_complexity: "O(N)", space_complexity: "O(1)", description: "Flip next pointers." }],
            },
            Problem::MergeTwoLists => ProblemDetails {
                id: 21, title: "Merge Two Sorted Linked Lists", difficulty: Difficulty::Easy, category: Category::LinkedList,
                statement: "Merge two sorted linked lists into one sorted list.",
                examples: &[Example { input: "list1 = [1, 2, 4], list2 = [1, 3, 5]", output: "[1, 1, 2, 3, 4, 5]", explanation: "Merged in order." }],
                constraints: &["0 <= list1.length <= 100"], leetcode_url: "https://leetcode.com/problems/merge-two-sorted-lists/",
                approaches: &[ApproachMeta { id: 0, name: "Two Pointers Merge", time_complexity: "O(N + M)", space_complexity: "O(1)", description: "Tail node attachments." }],
            },
            Problem::LinkedListCycle => ProblemDetails {
                id: 141, title: "Linked List Cycle Detection", difficulty: Difficulty::Easy, category: Category::LinkedList,
                statement: "Return true if there is a cycle in the linked list.",
                examples: &[Example { input: "head = [1, 2, 3, 4], index = 1", output: "true", explanation: "Tail connects to index 1." }],
                constraints: &["0 <= length <= 1000"], leetcode_url: "https://leetcode.com/problems/linked-list-cycle/",
                approaches: &[ApproachMeta { id: 0, name: "Floyd's Tortoise & Hare", time_complexity: "O(N)", space_complexity: "O(1)", description: "Slow and fast pointers." }],
            },
            Problem::InvertTree => ProblemDetails {
                id: 226, title: "Invert Binary Tree", difficulty: Difficulty::Easy, category: Category::Trees,
                statement: "Invert a binary tree (swap left and right subtrees for every node).",
                examples: &[Example { input: "root = [1, 2, 3, 4, 5, 6, 7]", output: "[1, 3, 2, 7, 6, 5, 4]", explanation: "Subtrees swapped." }],
                constraints: &["0 <= nodes <= 100"], leetcode_url: "https://leetcode.com/problems/invert-binary-tree/",
                approaches: &[ApproachMeta { id: 0, name: "Recursive DFS", time_complexity: "O(N)", space_complexity: "O(H)", description: "Post-order swap." }],
            },
            Problem::MaxDepthTree => ProblemDetails {
                id: 104, title: "Maximum Depth of Binary Tree", difficulty: Difficulty::Easy, category: Category::Trees,
                statement: "Return the maximum depth of a binary tree.",
                examples: &[Example { input: "root = [1, 2, 3, null, null, 4]", output: "3", explanation: "Longest path is 3 nodes." }],
                constraints: &["0 <= nodes <= 100"], leetcode_url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
                approaches: &[ApproachMeta { id: 0, name: "Recursive DFS", time_complexity: "O(N)", space_complexity: "O(H)", description: "1 + max(left, right)." }],
            },
            Problem::DiameterTree => ProblemDetails {
                id: 543, title: "Diameter of Binary Tree", difficulty: Difficulty::Easy, category: Category::Trees,
                statement: "Return length of longest path between any two nodes.",
                examples: &[Example { input: "root = [1, null, 2, 3, 4, 5]", output: "3", explanation: "Longest path has 3 edges." }],
                constraints: &["1 <= nodes <= 100"], leetcode_url: "https://leetcode.com/problems/diameter-of-binary-tree/",
                approaches: &[ApproachMeta { id: 0, name: "Post-order Depth DFS", time_complexity: "O(N)", space_complexity: "O(H)", description: "Left height + right height." }],
            },
            Problem::BalancedTree => ProblemDetails {
                id: 110, title: "Balanced Binary Tree", difficulty: Difficulty::Easy, category: Category::Trees,
                statement: "Determine if a binary tree is height-balanced (|height(left) - height(right)| <= 1).",
                examples: &[Example { input: "root = [3, 9, 20, null, null, 15, 7]", output: "true", explanation: "Balanced heights." }],
                constraints: &["0 <= nodes <= 5000"], leetcode_url: "https://leetcode.com/problems/balanced-binary-tree/",
                approaches: &[ApproachMeta { id: 0, name: "Bottom-Up Height DFS", time_complexity: "O(N)", space_complexity: "O(H)", description: "Check height difference at each node." }],
            },
            Problem::SameTree => ProblemDetails {
                id: 100, title: "Same Tree", difficulty: Difficulty::Easy, category: Category::Trees,
                statement: "Given roots of two binary trees p and q, return true if they are structural and value identical.",
                examples: &[Example { input: "p = [1, 2, 3], q = [1, 2, 3]", output: "true", explanation: "Trees match." }],
                constraints: &["0 <= nodes <= 100"], leetcode_url: "https://leetcode.com/problems/same-tree/",
                approaches: &[ApproachMeta { id: 0, name: "Recursive DFS Comparison", time_complexity: "O(N)", space_complexity: "O(H)", description: "Check p.val == q.val and recurse." }],
            },
            Problem::Subtree => ProblemDetails {
                id: 572, title: "Subtree of Another Tree", difficulty: Difficulty::Easy, category: Category::Trees,
                statement: "Return true if there is a subtree of root with the same structure and node values as subRoot.",
                examples: &[Example { input: "root = [3, 4, 5, 1, 2], subRoot = [4, 1, 2]", output: "true", explanation: "Subtree matches." }],
                constraints: &["0 <= nodes <= 2000"], leetcode_url: "https://leetcode.com/problems/subtree-of-another-tree/",
                approaches: &[ApproachMeta { id: 0, name: "DFS Tree Traversal & Match", time_complexity: "O(N * M)", space_complexity: "O(H)", description: "Check sameTree at each node." }],
            },
            Problem::ClimbingStairs => ProblemDetails {
                id: 70, title: "Climbing Stairs", difficulty: Difficulty::Easy, category: Category::OneDDp,
                statement: "It takes n steps to reach top. Each time you can climb 1 or 2 steps. How many distinct ways?",
                examples: &[Example { input: "n = 3", output: "3", explanation: "1+1+1, 1+2, 2+1." }],
                constraints: &["1 <= n <= 45"], leetcode_url: "https://leetcode.com/problems/climbing-stairs/",
                approaches: &[ApproachMeta { id: 0, name: "Dynamic Programming (Fibonacci)", time_complexity: "O(N)", space_complexity: "O(1)", description: "dp[i] = dp[i-1] + dp[i-2]." }],
            },
            Problem::MinCostStairs => ProblemDetails {
                id: 746, title: "Min Cost Climbing Stairs", difficulty: Difficulty::Easy, category: Category::OneDDp,
                statement: "Return minimum cost to reach top of floor by taking 1 or 2 steps.",
                examples: &[Example { input: "cost = [10, 15, 20]", output: "15", explanation: "Start at index 1, pay 15." }],
                constraints: &["2 <= cost.length <= 1000"], leetcode_url: "https://leetcode.com/problems/min-cost-climbing-stairs/",
                approaches: &[ApproachMeta { id: 0, name: "Bottom-Up DP", time_complexity: "O(N)", space_complexity: "O(1)", description: "dp[i] = min(dp[i-1]+cost[i-1], dp[i-2]+cost[i-2])." }],
            },
            Problem::KthLargestStream => ProblemDetails {
                id: 703, title: "Kth Largest Element in a Stream", difficulty: Difficulty::Easy, category: Category::HeapPriorityQueue,
                statement: "Design a class to find the k-th largest element in a stream.",
                examples: &[Example { input: "k = 3, nums = [4, 5, 8, 2], val = 3", output: "4", explanation: "Min-heap of size k=3." }],
                constraints: &["1 <= k <= 10^4"], leetcode_url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
                approaches: &[ApproachMeta { id: 0, name: "Min-Heap of Size k", time_complexity: "O(N log k)", space_complexity: "O(k)", description: "Maintain min-heap of size k." }],
            },
            Problem::LastStone => ProblemDetails {
                id: 1046, title: "Last Stone Weight", difficulty: Difficulty::Easy, category: Category::HeapPriorityQueue,
                statement: "Smash two heaviest stones y and x until at most 1 stone remains.",
                examples: &[Example { input: "stones = [2, 7, 4, 1, 8, 1]", output: "1", explanation: "Smash 8 and 7, remaining 1." }],
                constraints: &["1 <= stones.length <= 30"], leetcode_url: "https://leetcode.com/problems/last-stone-weight/",
                approaches: &[ApproachMeta { id: 0, name: "Max-Heap Simulation", time_complexity: "O(N log N)", space_complexity: "O(N)", description: "Repeatedly smash top 2." }],
            },
            Problem::MeetingRooms => ProblemDetails {
                id: 252, title: "Meeting Rooms", difficulty: Difficulty::Easy, category: Category::Intervals,
                statement: "Given an array of meeting time intervals, determine if a person could attend all meetings.",
                examples: &[Example { input: "intervals = [[0,30],[5,10],[15,20]]", output: "false", explanation: "[0,30] and [5,10] overlap." }],
                constraints: &["0 <= intervals.length <= 10^4"], leetcode_url: "https://leetcode.com/problems/meeting-rooms/",
                approaches: &[ApproachMeta { id: 0, name: "Sort Intervals by Start Time", time_complexity: "O(N log N)", space_complexity: "O(1)", description: "Check adjacent overlap." }],
            },
            Problem::HappyNumber => ProblemDetails {
                id: 202, title: "Happy Number", difficulty: Difficulty::Easy, category: Category::MathAndGeometry,
                statement: "Determine if a number n is happy (sum of square of digits reaches 1).",
                examples: &[Example { input: "n = 19", output: "true", explanation: "1^2+9^2=82 -> 68 -> 100 -> 1." }],
                constraints: &["1 <= n <= 2^31 - 1"], leetcode_url: "https://leetcode.com/problems/happy-number/",
                approaches: &[ApproachMeta { id: 0, name: "HashSet Cycle Detection", time_complexity: "O(log N)", space_complexity: "O(log N)", description: "Track seen square sums." }],
            },
            Problem::PlusOne => ProblemDetails {
                id: 66, title: "Plus One", difficulty: Difficulty::Easy, category: Category::MathAndGeometry,
                statement: "Increment the large integer represented as a digit array by one.",
                examples: &[Example { input: "digits = [1, 2, 3]", output: "[1, 2, 4]", explanation: "123 + 1 = 124." }],
                constraints: &["1 <= digits.length <= 100"], leetcode_url: "https://leetcode.com/problems/plus-one/",
                approaches: &[ApproachMeta { id: 0, name: "Right-to-Left Carry Pass", time_complexity: "O(N)", space_complexity: "O(1)", description: "Add 1 from right, carry overflow." }],
            },
            Problem::SingleNumber => ProblemDetails {
                id: 136, title: "Single Number", difficulty: Difficulty::Easy, category: Category::BitManipulation,
                statement: "Given a non-empty array of integers where every element appears twice except for one, find it.",
                examples: &[Example { input: "nums = [4, 1, 2, 1, 2]", output: "4", explanation: "4 is non-duplicate." }],
                constraints: &["1 <= nums.length <= 3*10^4"], leetcode_url: "https://leetcode.com/problems/single-number/",
                approaches: &[ApproachMeta { id: 0, name: "Bitwise XOR", time_complexity: "O(N)", space_complexity: "O(1)", description: "a ^ a = 0 cancels duplicates." }],
            },
            Problem::CountBits => ProblemDetails {
                id: 191, title: "Number of 1 Bits", difficulty: Difficulty::Easy, category: Category::BitManipulation,
                statement: "Return the number of set bits (1s) in a 32-bit unsigned integer.",
                examples: &[Example { input: "n = 11 (0000...1011)", output: "3", explanation: "3 set bits." }],
                constraints: &["1 <= n <= 2^31 - 1"], leetcode_url: "https://leetcode.com/problems/number-of-1-bits/",
                approaches: &[ApproachMeta { id: 0, name: "Brian Kernighan's Algorithm", time_complexity: "O(1)", space_complexity: "O(1)", description: "n &= n - 1 clears lowest 1 bit." }],
            },
            Problem::CountingBits => ProblemDetails {
                id: 338, title: "Counting Bits", difficulty: Difficulty::Easy, category: Category::BitManipulation,
                statement: "Given n, return an array ans of length n + 1 where ans[i] is the number of 1's in binary representation of i.",
                examples: &[Example { input: "n = 5", output: "[0,1,1,2,1,2]", explanation: "Bits for 0..5." }],
                constraints: &["0 <= n <= 10^5"], leetcode_url: "https://leetcode.com/problems/counting-bits/",
                approaches: &[ApproachMeta { id: 0, name: "Dynamic Programming (Bit Shift / Offset)", time_complexity: "O(N)", space_complexity: "O(N)", description: "dp[i] = 1 + dp[i - offset]." }],
            },
            Problem::ReverseBits => ProblemDetails {
                id: 190, title: "Reverse Bits", difficulty: Difficulty::Easy, category: Category::BitManipulation,
                statement: "Reverse bits of a given 32-bit unsigned integer.",
                examples: &[Example { input: "n = 43261596 (00000010100101000001111010011100)", output: "964176192", explanation: "Reversed bits." }],
                constraints: &["32-bit integer"], leetcode_url: "https://leetcode.com/problems/reverse-bits/",
                approaches: &[ApproachMeta { id: 0, name: "Bitwise Shift & Or", time_complexity: "O(1)", space_complexity: "O(1)", description: "Shift bit i to 31 - i." }],
            },
            Problem::MissingNumber => ProblemDetails {
                id: 268, title: "Missing Number", difficulty: Difficulty::Easy, category: Category::BitManipulation,
                statement: "Given an array containing n distinct numbers in range [0, n], return the missing number.",
                examples: &[Example { input: "nums = [3, 0, 1]", output: "2", explanation: "Range [0..3], 2 is missing." }],
                constraints: &["1 <= n <= 10^4"], leetcode_url: "https://leetcode.com/problems/missing-number/",
                approaches: &[ApproachMeta { id: 0, name: "Gauss Sum Formula", time_complexity: "O(N)", space_complexity: "O(1)", description: "expected_sum - actual_sum." }],
            },
            Problem::TwoSumII => ProblemDetails {
                id: 167, title: "Two Sum II - Input Array Is Sorted", difficulty: Difficulty::Medium, category: Category::TwoPointers,
                statement: "Given a 1-indexed array of integers that is already sorted in non-decreasing order, find two numbers such that they add up to a specific target number.",
                examples: &[Example { input: "numbers = [2, 7, 11, 15], target = 9", output: "[1, 2]", explanation: "numbers[1] + numbers[2] = 9." }],
                constraints: &["2 <= numbers.length <= 3*10^4", "numbers is sorted in non-decreasing order"], leetcode_url: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
                approaches: &[ApproachMeta { id: 0, name: "Two Pointers (Sorted)", time_complexity: "O(N)", space_complexity: "O(1)", description: "Left/right pointers converge on target sum." }],
            },
            Problem::ThreeSum => ProblemDetails {
                id: 15, title: "3Sum", difficulty: Difficulty::Medium, category: Category::TwoPointers,
                statement: "Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.",
                examples: &[Example { input: "nums = [-1, 0, 1, 2, -1, -4]", output: "[[-1, -1, 2], [-1, 0, 1]]", explanation: "Two unique triplets sum to 0." }],
                constraints: &["3 <= nums.length <= 3000"], leetcode_url: "https://leetcode.com/problems/3sum/",
                approaches: &[ApproachMeta { id: 0, name: "Sort + Two Pointers", time_complexity: "O(N^2)", space_complexity: "O(1)", description: "Fix anchor, two pointers for remaining pair." }],
            },
            Problem::ContainerWater => ProblemDetails {
                id: 11, title: "Container With Most Water", difficulty: Difficulty::Medium, category: Category::TwoPointers,
                statement: "Given n non-negative integers representing n vertical lines, find two lines that together with the x-axis form a container that holds the most water.",
                examples: &[Example { input: "height = [1, 8, 6, 2, 5, 4, 8, 3, 7]", output: "49", explanation: "Lines at index 1 and 8 form container of area 49." }],
                constraints: &["n == height.length", "2 <= n <= 10^5"], leetcode_url: "https://leetcode.com/problems/container-with-most-water/",
                approaches: &[ApproachMeta { id: 0, name: "Two Pointers Greedy", time_complexity: "O(N)", space_complexity: "O(1)", description: "Move the shorter line inward to maximize area." }],
            },
            Problem::TrappingRain => ProblemDetails {
                id: 42, title: "Trapping Rain Water", difficulty: Difficulty::Hard, category: Category::TwoPointers,
                statement: "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.",
                examples: &[Example { input: "height = [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]", output: "6", explanation: "6 units of rain water are trapped." }],
                constraints: &["n == height.length", "0 <= n <= 2*10^4"], leetcode_url: "https://leetcode.com/problems/trapping-rain-water/",
                approaches: &[ApproachMeta { id: 0, name: "Two Pointers (leftMax / rightMax)", time_complexity: "O(N)", space_complexity: "O(1)", description: "Track max heights from both sides." }],
            },
            Problem::MinStack => ProblemDetails {
                id: 155, title: "Min Stack", difficulty: Difficulty::Medium, category: Category::Stack,
                statement: "Design a stack that supports push, pop, top, and retrieving the minimum element in constant time O(1).",
                examples: &[Example { input: "push(-2), push(0), push(-3), getMin(), pop(), top(), getMin()", output: "getMin() = -3, top() = 0, getMin() = -2", explanation: "Min stack tracks minimum element at every push level." }],
                constraints: &["-2^31 <= val <= 2^31 - 1", "Methods pop, top and getMin will always be called on non-empty stacks"], leetcode_url: "https://leetcode.com/problems/min-stack/",
                approaches: &[ApproachMeta { id: 0, name: "Two Stacks (Value + MinStack)", time_complexity: "O(1)", space_complexity: "O(N)", description: "Maintain parallel stack tracking minimums." }],
            },
            Problem::EvalRPN => ProblemDetails {
                id: 150, title: "Evaluate Reverse Polish Notation", difficulty: Difficulty::Medium, category: Category::Stack,
                statement: "Evaluate the value of an arithmetic expression in Reverse Polish Notation (postfix). Valid operators are +, -, *, and /.",
                examples: &[Example { input: "tokens = [\"2\", \"1\", \"+\", \"3\", \"*\"]", output: "9", explanation: "((2 + 1) * 3) = 9." }],
                constraints: &["1 <= tokens.length <= 10^4", "tokens[i] is an operator or integer in range [-200, 200]"], leetcode_url: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
                approaches: &[ApproachMeta { id: 0, name: "Stack Operand Evaluation", time_complexity: "O(N)", space_complexity: "O(N)", description: "Push numbers, pop 2 numbers on operator." }],
            },
            Problem::LongestSubstring => ProblemDetails {
                id: 3, title: "Longest Substring Without Repeating Characters", difficulty: Difficulty::Medium, category: Category::SlidingWindow,
                statement: "Given a string s, find the length of the longest substring without repeating characters.",
                examples: &[Example { input: "s = \"abcabcbb\"", output: "3", explanation: "The answer is \"abc\", with length 3." }],
                constraints: &["0 <= s.length <= 5*10^4"], leetcode_url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
                approaches: &[ApproachMeta { id: 0, name: "Sliding Window Set", time_complexity: "O(N)", space_complexity: "O(N)", description: "Expand right, shrink left on duplicate." }],
            },
            Problem::Search2DMatrix => ProblemDetails {
                id: 74, title: "Search a 2D Matrix", difficulty: Difficulty::Medium, category: Category::BinarySearch,
                statement: "Write an efficient algorithm that searches for a target value in an m x n integer matrix with sorted rows and columns.",
                examples: &[Example { input: "matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3", output: "true", explanation: "3 exists in row 0, col 1." }],
                constraints: &["m == matrix.length", "n == matrix[i].length", "1 <= m, n <= 100"], leetcode_url: "https://leetcode.com/problems/search-a-2d-matrix/",
                approaches: &[ApproachMeta { id: 0, name: "Binary Search Virtual 1D Array", time_complexity: "O(log(M*N))", space_complexity: "O(1)", description: "Map mid index to matrix[mid / cols][mid % cols]." }],
            },
            Problem::HouseRobber => ProblemDetails {
                id: 198, title: "House Robber", difficulty: Difficulty::Medium, category: Category::OneDDp,
                statement: "Given an integer array nums representing the amount of money of each house, return the maximum amount of money you can rob tonight without robbing adjacent houses.",
                examples: &[Example { input: "nums = [1, 2, 3, 1]", output: "4", explanation: "Rob house 1 (money = 1) and rob house 3 (money = 3). Total = 1 + 3 = 4." }],
                constraints: &["1 <= nums.length <= 100"], leetcode_url: "https://leetcode.com/problems/house-robber/",
                approaches: &[ApproachMeta { id: 0, name: "Bottom-Up Dynamic Programming", time_complexity: "O(N)", space_complexity: "O(1)", description: "dp[i] = max(dp[i-1], dp[i-2] + nums[i])." }],
            },
            Problem::GenerateParentheses => ProblemDetails {
                id: 22, title: "Generate Parentheses", difficulty: Difficulty::Medium, category: Category::Stack,
                statement: "Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.",
                examples: &[Example { input: "n = 3", output: "[\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]", explanation: "All 5 valid combinations." }],
                constraints: &["1 <= n <= 8"], leetcode_url: "https://leetcode.com/problems/generate-parentheses/",
                approaches: &[ApproachMeta { id: 0, name: "Backtracking / Stack", time_complexity: "O(4^N / sqrt(N))", space_complexity: "O(N)", description: "Recursively build string adhering to open < n and close < open." }],
            },
            Problem::DailyTemperatures => ProblemDetails {
                id: 739, title: "Daily Temperatures", difficulty: Difficulty::Medium, category: Category::Stack,
                statement: "Given an array of integers temperatures represents the daily temperatures, return an array answer such that answer[i] is the number of days you have to wait after the i-th day to get a warmer temperature.",
                examples: &[Example { input: "temperatures = [73, 74, 75, 71, 69, 72, 76, 73]", output: "[1, 1, 4, 2, 1, 1, 0, 0]", explanation: "Monotonic stack tracking waiting days." }],
                constraints: &["1 <= temperatures.length <= 10^5", "30 <= temperatures[i] <= 100"], leetcode_url: "https://leetcode.com/problems/daily-temperatures/",
                approaches: &[ApproachMeta { id: 0, name: "Monotonic Decreasing Stack", time_complexity: "O(N)", space_complexity: "O(N)", description: "Maintain stack of indices in decreasing temperature order." }],
            },
            Problem::CarFleet => ProblemDetails {
                id: 853, title: "Car Fleet", difficulty: Difficulty::Medium, category: Category::Stack,
                statement: "There are n cars at given miles away from the starting mile 0, traveling to a destination target. Return the number of car fleets that will arrive at the destination.",
                examples: &[Example { input: "target = 12, position = [10,8,0,5,3], speed = [2,4,1,1,3]", output: "3", explanation: "Cars starting at 10 and 8 merge into 1 fleet, 5 and 3 merge into 1 fleet, 0 drives alone." }],
                constraints: &["n == position.length == speed.length", "1 <= n <= 10^5"], leetcode_url: "https://leetcode.com/problems/car-fleet/",
                approaches: &[ApproachMeta { id: 0, name: "Monotonic Time Stack (Position Order)", time_complexity: "O(N log N)", space_complexity: "O(N)", description: "Sort by position desc, pop if car behind catches up." }],
            },
            Problem::LargestRectangle => ProblemDetails {
                id: 84, title: "Largest Rectangle in Histogram", difficulty: Difficulty::Hard, category: Category::Stack,
                statement: "Given an array of integers heights representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.",
                examples: &[Example { input: "heights = [2, 1, 5, 6, 2, 3]", output: "10", explanation: "The largest rectangle has area = 10 units (heights 5 and 6)." }],
                constraints: &["1 <= heights.length <= 10^5", "0 <= heights[i] <= 10^4"], leetcode_url: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
                approaches: &[ApproachMeta { id: 0, name: "Monotonic Increasing Stack", time_complexity: "O(N)", space_complexity: "O(N)", description: "Maintain (index, height) pair stack, compute max area on pop." }],
            },
            Problem::CharacterReplacement => ProblemDetails {
                id: 424, title: "Longest Repeating Character Replacement", difficulty: Difficulty::Medium, category: Category::SlidingWindow,
                statement: "You are given a string s and an integer k. You can choose any character of the string and change it to any other uppercase English character at most k times. Return the length of the longest substring containing the same letter.",
                examples: &[Example { input: "s = \"ABAB\", k = 2", output: "4", explanation: "Replace the two 'A's with 'B's or vice versa." }],
                constraints: &["1 <= s.length <= 10^5", "0 <= k <= s.length"], leetcode_url: "https://leetcode.com/problems/longest-repeating-character-replacement/",
                approaches: &[ApproachMeta { id: 0, name: "Sliding Window Frequency Map", time_complexity: "O(N)", space_complexity: "O(26)", description: "Maintain max frequency, shrink left when (window_len - max_freq) > k." }],
            },
            Problem::PermutationInString => ProblemDetails {
                id: 567, title: "Permutation in String", difficulty: Difficulty::Medium, category: Category::SlidingWindow,
                statement: "Given two strings s1 and s2, return true if s2 contains a permutation of s1, or false otherwise.",
                examples: &[Example { input: "s1 = \"ab\", s2 = \"eidbaooo\"", output: "true", explanation: "s2 contains one permutation of s1 (\"ba\")." }],
                constraints: &["1 <= s1.length, s2.length <= 10^4"], leetcode_url: "https://leetcode.com/problems/permutation-in-string/",
                approaches: &[ApproachMeta { id: 0, name: "Fixed Size Sliding Window Matches Count", time_complexity: "O(N)", space_complexity: "O(26)", description: "Slide window of size len(s1), track matching char counts." }],
            },
            Problem::MinWindowSubstring => ProblemDetails {
                id: 76, title: "Minimum Window Substring", difficulty: Difficulty::Hard, category: Category::SlidingWindow,
                statement: "Given two strings s and t of lengths m and n respectively, return the minimum window substring of s such that every character in t (including duplicates) is included in the window.",
                examples: &[Example { input: "s = \"ADOBECODEBANC\", t = \"ABC\"", output: "\"BANC\"", explanation: "The minimum window substring \"BANC\" includes 'A', 'B', and 'C' from string t." }],
                constraints: &["m == s.length", "n == t.length", "1 <= m, n <= 10^5"], leetcode_url: "https://leetcode.com/problems/minimum-window-substring/",
                approaches: &[ApproachMeta { id: 0, name: "Dynamic Sliding Window Have/Need Map", time_complexity: "O(N)", space_complexity: "O(M+N)", description: "Expand right until valid, then shrink left to minimize window." }],
            },
            Problem::SlidingWindowMax => ProblemDetails {
                id: 239, title: "Sliding Window Maximum", difficulty: Difficulty::Hard, category: Category::SlidingWindow,
                statement: "You are given an array of integers nums, there is a sliding window of size k which is moving from the very left of the array to the very right. Return the max sliding window.",
                examples: &[Example { input: "nums = [1,3,-1,-3,5,3,6,7], k = 3", output: "[3,3,5,5,6,7]", explanation: "Monotonic deque tracks sliding window maximum in O(N)." }],
                constraints: &["1 <= nums.length <= 10^5", "1 <= k <= nums.length"], leetcode_url: "https://leetcode.com/problems/sliding-window-maximum/",
                approaches: &[ApproachMeta { id: 0, name: "Monotonic Decreasing Deque", time_complexity: "O(N)", space_complexity: "O(k)", description: "Maintain deque of indices with strictly decreasing values." }],
            },
        }
    }
}

// ── Visual State Variants per Problem Type ──

#[derive(Debug, Clone)]
pub enum VisualState {
    ContainsDuplicate {
        nums: Vec<i32>,
        active_idx: Option<usize>,
        seen_set: BTreeSet<i32>,
        duplicate_val: Option<i32>,
        has_duplicate: Option<bool>,
    },
    GroupAnagrams {
        input_strs: Vec<String>,
        active_idx: Option<usize>,
        key_fmt: String,
        groups: BTreeMap<String, Vec<String>>,
    },
    TopK {
        nums: Vec<i32>,
        active_nums_idx: Option<usize>,
        count_map: BTreeMap<i32, usize>,
        buckets: Vec<Vec<i32>>,
        active_bucket_idx: Option<usize>,
        result: Vec<i32>,
    },
    EncodeDecode {
        input_strs: Vec<String>,
        encoded_so_far: String,
        decoded_so_far: Vec<String>,
        pointer: usize,
        active_str_idx: Option<usize>,
        phase: EncodeDecodePhase,
    },
    Product {
        nums: Vec<i32>,
        output: Vec<i64>,
        active_idx: Option<usize>,
        prefix_val: i64,
        suffix_val: i64,
        phase: ProductPhase,
    },
    ValidSudoku {
        board: [[char; 9]; 9],
        active_r: Option<usize>,
        active_c: Option<usize>,
        duplicate_pos: Option<(usize, usize)>,
        is_valid: Option<bool>,
    },
    LongestConsecutive {
        nums: Vec<i32>,
        num_set: BTreeSet<i32>,
        current_num: Option<i32>,
        current_seq: Vec<i32>,
        max_length: usize,
        is_seq_start: Option<bool>,
    },
    TwoSum {
        nums: Vec<i32>,
        target: i32,
        active_idx: Option<usize>,
        secondary_idx: Option<usize>,
        map: BTreeMap<i32, usize>,
        found_indices: Option<(usize, usize)>,
    },
    ValidAnagram {
        s: String,
        t: String,
        s_counts: [usize; 26],
        t_counts: [usize; 26],
        active_s_idx: Option<usize>,
        active_t_idx: Option<usize>,
        is_anagram: Option<bool>,
    },
    TwoPointers {
        chars: Vec<char>,
        left: usize,
        right: usize,
        is_valid: Option<bool>,
        skipped: bool,
    },
    Stack {
        chars: Vec<char>,
        active_idx: Option<usize>,
        stack: Vec<char>,
        is_valid: Option<bool>,
    },
    BestTimeStock {
        prices: Vec<i32>,
        left_buy: usize,
        right_sell: usize,
        current_profit: i32,
        max_profit: i32,
    },
    BinarySearch {
        nums: Vec<i32>,
        target: i32,
        left: usize,
        right: usize,
        mid: Option<usize>,
        found_idx: Option<usize>,
    },
    LinkedList {
        nodes: Vec<i32>,
        prev_idx: Option<usize>,
        curr_idx: Option<usize>,
        next_idx: Option<usize>,
        reversed_so_far: Vec<i32>,
    },
    MergeLinkedLists {
        list1: Vec<i32>,
        list2: Vec<i32>,
        p1_idx: Option<usize>,
        p2_idx: Option<usize>,
        merged_so_far: Vec<i32>,
    },
    LinkedListCycle {
        nodes: Vec<i32>,
        cycle_target_idx: Option<usize>,
        slow_idx: Option<usize>,
        fast_idx: Option<usize>,
        has_cycle: Option<bool>,
    },
    TreeVisual {
        tree_nodes: Vec<Option<i32>>,
        active_node_idx: Option<usize>,
        secondary_node_idx: Option<usize>,
        depth_val: Option<i32>,
        max_diameter: Option<i32>,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EncodeDecodePhase {
    Init,
    Encoding,
    EncodingComplete,
    Decoding,
    Complete,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProductPhase {
    Init,
    PrefixPass,
    SuffixPass,
    Complete,
}

// ── Generic Execution Step ──

#[derive(Debug, Clone)]
pub struct Step {
    pub code_line: usize,
    pub description: String,
    pub visual: VisualState,
}

// ── Approach-Specific Code Lines Providers ──

pub fn approach_code_lines(problem: Problem, approach_id: usize) -> Vec<(usize, &'static str)> {
    match (problem, approach_id) {
        (Problem::ContainsDuplicate, 0) => vec![
            (1, "class Solution:"),
            (2, "    def containsDuplicate(self, nums: List[int]) -> bool:"),
            (3, "        seen = set()"),
            (4, "        for n in nums:"),
            (5, "            if n in seen:"),
            (6, "                return True"),
            (7, "            seen.add(n)"),
            (8, "        return False"),
        ],
        (Problem::TwoSum, 0) => vec![
            (1, "class Solution:"),
            (2, "    def twoSum(self, nums: List[int], target: int) -> List[int]:"),
            (3, "        prevMap = {} # val -> index"),
            (4, "        for i, n in enumerate(nums):"),
            (5, "            diff = target - n"),
            (6, "            if diff in prevMap:"),
            (7, "                return [prevMap[diff], i]"),
            (8, "            prevMap[n] = i"),
            (9, "        return []"),
        ],
        (Problem::ValidAnagram, 0) => vec![
            (1, "class Solution:"),
            (2, "    def isAnagram(self, s: str, t: str) -> bool:"),
            (3, "        if len(s) != len(t): return False"),
            (4, "        countS, countT = {}, {}"),
            (5, "        for i in range(len(s)):"),
            (6, "            countS[s[i]] = 1 + countS.get(s[i], 0)"),
            (7, "            countT[t[i]] = 1 + countT.get(t[i], 0)"),
            (8, "        return countS == countT"),
        ],
        (Problem::GroupAnagrams, 0) => vec![
            (1, "class Solution:"),
            (2, "    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:"),
            (3, "        res = defaultdict(list)"),
            (4, "        for s in strs:"),
            (5, "            count = [0] * 26"),
            (6, "            for c in s: count[ord(c) - ord('a')] += 1"),
            (7, "            res[tuple(count)].append(s)"),
            (8, "        return list(res.values())"),
        ],
        (Problem::TopKFrequent, 0) => crate::model::topk_code_lines(),
        (Problem::ProductExceptSelf, _) => crate::model::product_code_lines(),
        (Problem::EncodeDecode, _) => crate::model::encode_decode_code_lines(),
        (Problem::ValidSudoku, _) => vec![
            (1, "class Solution:"),
            (2, "    def isValidSudoku(self, board: List[List[str]]) -> bool:"),
            (3, "        rows, cols, squares = defaultdict(set), defaultdict(set), defaultdict(set)"),
            (4, "        for r in range(9):"),
            (5, "            for c in range(9):"),
            (6, "                if board[r][c] == '.': continue"),
            (7, "                val = board[r][c]"),
            (8, "                if val in rows[r] or val in cols[c] or val in squares[(r//3, c//3)]: return False"),
            (9, "                rows[r].add(val); cols[c].add(val); squares[(r//3, c//3)].add(val)"),
            (10, "        return True"),
        ],
        (Problem::LongestConsecutive, _) => vec![
            (1, "class Solution:"),
            (2, "    def longestConsecutive(self, nums: List[int]) -> int:"),
            (3, "        numSet = set(nums); longest = 0"),
            (4, "        for n in numSet:"),
            (5, "            if (n - 1) not in numSet:"),
            (6, "                length = 1"),
            (7, "                while (n + length) in numSet: length += 1"),
            (8, "                longest = max(longest, length)"),
            (9, "        return longest"),
        ],
        (Problem::ValidPalindrome, 0) => vec![
            (1, "class Solution:"),
            (2, "    def isPalindrome(self, s: str) -> bool:"),
            (3, "        l, r = 0, len(s) - 1"),
            (4, "        while l < r:"),
            (5, "            while l < r and not s[l].isalnum(): l += 1"),
            (6, "            while r > l and not s[r].isalnum(): r -= 1"),
            (7, "            if s[l].lower() != s[r].lower(): return False"),
            (8, "            l, r = l + 1, r - 1"),
            (9, "        return True"),
        ],
        (Problem::BestTimeStock, _) => vec![
            (1, "class Solution:"),
            (2, "    def maxProfit(self, prices: List[int]) -> int:"),
            (3, "        l, r = 0, 1; maxP = 0"),
            (4, "        while r < len(prices):"),
            (5, "            if prices[l] < prices[r]:"),
            (6, "                maxP = max(maxP, prices[r] - prices[l])"),
            (7, "            else: l = r"),
            (8, "            r += 1"),
            (9, "        return maxP"),
        ],
        (Problem::ValidParentheses, _) => vec![
            (1, "class Solution:"),
            (2, "    def isValid(self, s: str) -> bool:"),
            (3, "        stack = []"),
            (4, "        closeToOpen = {\")\": \"(\", \"]\": \"[\", \"}\": \"{\"}"),
            (5, "        for c in s:"),
            (6, "            if c in closeToOpen:"),
            (7, "                if stack and stack[-1] == closeToOpen[c]: stack.pop()"),
            (8, "                else: return False"),
            (9, "            else: stack.append(c)"),
            (10, "        return True if not stack else False"),
        ],
        (Problem::BinarySearch, _) => vec![
            (1, "class Solution:"),
            (2, "    def search(self, nums: List[int], target: int) -> int:"),
            (3, "        l, r = 0, len(nums) - 1"),
            (4, "        while l <= r:"),
            (5, "            m = l + ((r - l) // 2)"),
            (6, "            if nums[m] > target: r = m - 1"),
            (7, "            elif nums[m] < target: l = m + 1"),
            (8, "            else: return m"),
            (9, "        return -1"),
        ],
        (Problem::ReverseLinkedList, _) => vec![
            (1, "class Solution:"),
            (2, "    def reverseList(self, head: Optional[ListNode]) -> Optional[ListNode]:"),
            (3, "        prev, curr = None, head"),
            (4, "        while curr:"),
            (5, "            nxt = curr.next; curr.next = prev; prev = curr; curr = nxt"),
            (6, "        return prev"),
        ],
        (Problem::MergeTwoLists, _) => vec![
            (1, "class Solution:"),
            (2, "    def mergeTwoLists(self, list1: Optional[ListNode], list2: Optional[ListNode]) -> Optional[ListNode]:"),
            (3, "        dummy = tail = ListNode()"),
            (4, "        while list1 and list2:"),
            (5, "            if list1.val < list2.val: tail.next = list1; list1 = list1.next"),
            (6, "            else: tail.next = list2; list2 = list2.next"),
            (7, "            tail = tail.next"),
            (8, "        tail.next = list1 if list1 else list2"),
            (9, "        return dummy.next"),
        ],
        (Problem::LinkedListCycle, _) => vec![
            (1, "class Solution:"),
            (2, "    def hasCycle(self, head: Optional[ListNode]) -> bool:"),
            (3, "        slow, fast = head, head"),
            (4, "        while fast and fast.next:"),
            (5, "            slow = slow.next; fast = fast.next.next"),
            (6, "            if slow == fast: return True"),
            (7, "        return False"),
        ],
        (Problem::InvertTree, _) => vec![
            (1, "class Solution:"),
            (2, "    def invertTree(self, root: Optional[TreeNode]) -> Optional[TreeNode]:"),
            (3, "        if not root: return None"),
            (4, "        tmp = root.left; root.left = root.right; root.right = tmp"),
            (5, "        self.invertTree(root.left); self.invertTree(root.right)"),
            (6, "        return root"),
        ],
        (Problem::MaxDepthTree, _) => vec![
            (1, "class Solution:"),
            (2, "    def maxDepth(self, root: Optional[TreeNode]) -> int:"),
            (3, "        if not root: return 0"),
            (4, "        return 1 + max(self.maxDepth(root.left), self.maxDepth(root.right))"),
        ],
        (Problem::DiameterTree, _) => vec![
            (1, "class Solution:"),
            (2, "    def diameterOfBinaryTree(self, root: Optional[TreeNode]) -> int:"),
            (3, "        res = 0"),
            (4, "        def dfs(curr):"),
            (5, "            nonlocal res"),
            (6, "            if not curr: return 0"),
            (7, "            left, right = dfs(curr.left), dfs(curr.right)"),
            (8, "            res = max(res, left + right)"),
            (9, "            return 1 + max(left, right)"),
            (10, "        dfs(root); return res"),
        ],
        (Problem::BalancedTree, _) => vec![
            (1, "class Solution:"),
            (2, "    def isBalanced(self, root: Optional[TreeNode]) -> bool:"),
            (3, "        def dfs(root):"),
            (4, "            if not root: return [True, 0]"),
            (5, "            left, right = dfs(root.left), dfs(root.right)"),
            (6, "            balanced = left[0] and right[0] and abs(left[1] - right[1]) <= 1"),
            (7, "            return [balanced, 1 + max(left[1], right[1])]"),
            (8, "        return dfs(root)[0]"),
        ],
        (Problem::SameTree, _) => vec![
            (1, "class Solution:"),
            (2, "    def isSameTree(self, p: Optional[TreeNode], q: Optional[TreeNode]) -> bool:"),
            (3, "        if not p and not q: return True"),
            (4, "        if not p or not q or p.val != q.val: return False"),
            (5, "        return self.isSameTree(p.left, q.left) and self.isSameTree(p.right, q.right)"),
        ],
        (Problem::Subtree, _) => vec![
            (1, "class Solution:"),
            (2, "    def isSubtree(self, root: Optional[TreeNode], subRoot: Optional[TreeNode]) -> bool:"),
            (3, "        if not subRoot: return True"),
            (4, "        if not root: return False"),
            (5, "        if self.sameTree(root, subRoot): return True"),
            (6, "        return self.isSubtree(root.left, subRoot) or self.isSubtree(root.right, subRoot)"),
        ],
        (Problem::ClimbingStairs, _) => vec![
            (1, "class Solution:"),
            (2, "    def climbStairs(self, n: int) -> int:"),
            (3, "        one, two = 1, 1"),
            (4, "        for i in range(n - 1):"),
            (5, "            temp = one; one = one + two; two = temp"),
            (6, "        return one"),
        ],
        (Problem::MinCostStairs, _) => vec![
            (1, "class Solution:"),
            (2, "    def minCostClimbingStairs(self, cost: List[int]) -> int:"),
            (3, "        cost.append(0)"),
            (4, "        for i in range(len(cost) - 3, -1, -1):"),
            (5, "            cost[i] += min(cost[i + 1], cost[i + 2])"),
            (6, "        return min(cost[0], cost[1])"),
        ],
        (Problem::KthLargestStream, _) => vec![
            (1, "class KthLargest:"),
            (2, "    def __init__(self, k: int, nums: List[int]):"),
            (3, "        self.minHeap, self.k = nums, k"),
            (4, "        heapq.heapify(self.minHeap)"),
            (5, "        while len(self.minHeap) > k: heapq.heappop(self.minHeap)"),
            (6, "    def add(self, val: int) -> int:"),
            (7, "        heapq.heappush(self.minHeap, val)"),
            (8, "        if len(self.minHeap) > self.k: heapq.heappop(self.minHeap)"),
            (9, "        return self.minHeap[0]"),
        ],
        (Problem::LastStone, _) => vec![
            (1, "class Solution:"),
            (2, "    def lastStoneWeight(self, stones: List[int]) -> int:"),
            (3, "        stones = [-s for s in stones]"),
            (4, "        heapq.heapify(stones)"),
            (5, "        while len(stones) > 1:"),
            (6, "            first = heapq.heappop(stones); second = heapq.heappop(stones)"),
            (7, "            if second > first: heapq.heappush(stones, first - second)"),
            (8, "        stones.append(0)"),
            (9, "        return abs(stones[0])"),
        ],
        (Problem::MeetingRooms, _) => vec![
            (1, "class Solution:"),
            (2, "    def canAttendMeetings(self, intervals: List[Interval]) -> bool:"),
            (3, "        intervals.sort(key=lambda i: i.start)"),
            (4, "        for i in range(1, len(intervals)):"),
            (5, "            if intervals[i].start < intervals[i - 1].end: return False"),
            (6, "        return True"),
        ],
        (Problem::HappyNumber, _) => vec![
            (1, "class Solution:"),
            (2, "    def isHappy(self, n: int) -> bool:"),
            (3, "        visit = set()"),
            (4, "        while n not in visit:"),
            (5, "            visit.add(n); n = self.sumOfSquares(n)"),
            (6, "            if n == 1: return True"),
            (7, "        return False"),
        ],
        (Problem::PlusOne, _) => vec![
            (1, "class Solution:"),
            (2, "    def plusOne(self, digits: List[int]) -> List[int]:"),
            (3, "        for i in range(len(digits) - 1, -1, -1):"),
            (4, "            if digits[i] < 9: digits[i] += 1; return digits"),
            (5, "            digits[i] = 0"),
            (6, "        return [1] + digits"),
        ],
        (Problem::SingleNumber, _) => vec![
            (1, "class Solution:"),
            (2, "    def singleNumber(self, nums: List[int]) -> int:"),
            (3, "        res = 0"),
            (4, "        for n in nums: res ^= n"),
            (5, "        return res"),
        ],
        (Problem::CountBits, _) => vec![
            (1, "class Solution:"),
            (2, "    def hammingWeight(self, n: int) -> int:"),
            (3, "        res = 0"),
            (4, "        while n: n &= (n - 1); res += 1"),
            (5, "        return res"),
        ],
        (Problem::CountingBits, _) => vec![
            (1, "class Solution:"),
            (2, "    def countBits(self, n: int) -> List[int]:"),
            (3, "        dp = [0] * (n + 1); offset = 1"),
            (4, "        for i in range(1, n + 1):"),
            (5, "            if offset * 2 == i: offset = i"),
            (6, "            dp[i] = 1 + dp[i - offset]"),
            (7, "        return dp"),
        ],
        (Problem::ReverseBits, _) => vec![
            (1, "class Solution:"),
            (2, "    def reverseBits(self, n: int) -> int:"),
            (3, "        res = 0"),
            (4, "        for i in range(32):"),
            (5, "            bit = (n >> i) & 1; res |= (bit << (31 - i))"),
            (6, "        return res"),
        ],
        (Problem::MissingNumber, _) => vec![
            (1, "class Solution:"),
            (2, "    def missingNumber(self, nums: List[int]) -> int:"),
            (3, "        res = len(nums)"),
            (4, "        for i in range(len(nums)): res += (i - nums[i])"),
            (5, "        return res"),
        ],
        (Problem::TwoSumII, _) => vec![
            (1, "class Solution:"),
            (2, "    def twoSum(self, numbers: List[int], target: int) -> List[int]:"),
            (3, "        l, r = 0, len(numbers) - 1"),
            (4, "        while l < r:"),
            (5, "            curSum = numbers[l] + numbers[r]"),
            (6, "            if curSum == target: return [l + 1, r + 1]"),
            (7, "            elif curSum < target: l += 1"),
            (8, "            else: r -= 1"),
            (9, "        return []"),
        ],
        (Problem::ThreeSum, _) => vec![
            (1, "class Solution:"),
            (2, "    def threeSum(self, nums: List[int]) -> List[List[int]]:"),
            (3, "        res = []; nums.sort()"),
            (4, "        for i, a in enumerate(nums):"),
            (5, "            if i > 0 and a == nums[i - 1]: continue"),
            (6, "            l, r = i + 1, len(nums) - 1"),
            (7, "            while l < r:"),
            (8, "                threeSum = a + nums[l] + nums[r]"),
            (9, "                if threeSum < 0: l += 1"),
            (10, "                elif threeSum > 0: r -= 1"),
            (11, "                else:"),
            (12, "                    res.append([a, nums[l], nums[r]]); l += 1"),
            (13, "                    while nums[l] == nums[l - 1] and l < r: l += 1"),
            (14, "        return res"),
        ],
        (Problem::ContainerWater, _) => vec![
            (1, "class Solution:"),
            (2, "    def maxArea(self, height: List[int]) -> int:"),
            (3, "        l, r = 0, len(height) - 1"),
            (4, "        res = 0"),
            (5, "        while l < r:"),
            (6, "            area = (r - l) * min(height[l], height[r])"),
            (7, "            res = max(res, area)"),
            (8, "            if height[l] < height[r]: l += 1"),
            (9, "            else: r -= 1"),
            (10, "        return res"),
        ],
        (Problem::TrappingRain, _) => vec![
            (1, "class Solution:"),
            (2, "    def trap(self, height: List[int]) -> int:"),
            (3, "        if not height: return 0"),
            (4, "        l, r = 0, len(height) - 1"),
            (5, "        leftMax, rightMax = height[l], height[r]"),
            (6, "        res = 0"),
            (7, "        while l < r:"),
            (8, "            if leftMax < rightMax:"),
            (9, "                l += 1; leftMax = max(leftMax, height[l]); res += leftMax - height[l]"),
            (10, "            else:"),
            (11, "                r -= 1; rightMax = max(rightMax, height[r]); res += rightMax - height[r]"),
            (12, "        return res"),
        ],
        (Problem::MinStack, _) => vec![
            (1, "class MinStack:"),
            (2, "    def __init__(self):"),
            (3, "        self.stack = []"),
            (4, "        self.minStack = []"),
            (5, "    def push(self, val: int) -> None:"),
            (6, "        self.stack.append(val)"),
            (7, "        val = min(val, self.minStack[-1] if self.minStack else val)"),
            (8, "        self.minStack.append(val)"),
            (9, "    def pop(self) -> None:"),
            (10, "        self.stack.pop(); self.minStack.pop()"),
            (11, "    def top(self) -> int: return self.stack[-1]"),
            (12, "    def getMin(self) -> int: return self.minStack[-1]"),
        ],
        (Problem::EvalRPN, _) => vec![
            (1, "class Solution:"),
            (2, "    def evalRPN(self, tokens: List[str]) -> int:"),
            (3, "        stack = []"),
            (4, "        for c in tokens:"),
            (5, "            if c == '+': stack.append(stack.pop() + stack.pop())"),
            (6, "            elif c == '-': a, b = stack.pop(), stack.pop(); stack.append(b - a)"),
            (7, "            elif c == '*': stack.append(stack.pop() * stack.pop())"),
            (8, "            elif c == '/': a, b = stack.pop(), stack.pop(); stack.append(int(b / a))"),
            (9, "            else: stack.append(int(c))"),
            (10, "        return stack[0]"),
        ],
        (Problem::LongestSubstring, _) => vec![
            (1, "class Solution:"),
            (2, "    def lengthOfLongestSubstring(self, s: str) -> int:"),
            (3, "        charSet = set(); l = 0; res = 0"),
            (4, "        for r in range(len(s)):"),
            (5, "            while s[r] in charSet:"),
            (6, "                charSet.remove(s[l]); l += 1"),
            (7, "            charSet.add(s[r])"),
            (8, "            res = max(res, r - l + 1)"),
            (9, "        return res"),
        ],
        (Problem::Search2DMatrix, _) => vec![
            (1, "class Solution:"),
            (2, "    def searchMatrix(self, matrix: List[List[int]], target: int) -> bool:"),
            (3, "        ROWS, COLS = len(matrix), len(matrix[0])"),
            (4, "        l, r = 0, ROWS * COLS - 1"),
            (5, "        while l <= r:"),
            (6, "            m = (l + r) // 2"),
            (7, "            row, col = m // COLS, m % COLS"),
            (8, "            if target > matrix[row][col]: l = m + 1"),
            (9, "            elif target < matrix[row][col]: r = m - 1"),
            (10, "            else: return True"),
            (11, "        return False"),
        ],
        (Problem::HouseRobber, _) => vec![
            (1, "class Solution:"),
            (2, "    def rob(self, nums: List[int]) -> int:"),
            (3, "        rob1, rob2 = 0, 0"),
            (4, "        for n in nums:"),
            (5, "            temp = max(n + rob1, rob2)"),
            (6, "            rob1 = rob2; rob2 = temp"),
            (7, "        return rob2"),
        ],
        (Problem::GenerateParentheses, _) => vec![
            (1, "class Solution:"),
            (2, "    def generateParenthesis(self, n: int) -> List[str]:"),
            (3, "        stack = []; res = []"),
            (4, "        def backtrack(openN, closedN):"),
            (5, "            if openN == closedN == n: res.append(\"\".join(stack)); return"),
            (6, "            if openN < n: stack.append(\"(\"); backtrack(openN + 1, closedN); stack.pop()"),
            (7, "            if closedN < openN: stack.append(\")\"); backtrack(openN, closedN + 1); stack.pop()"),
            (8, "        backtrack(0, 0); return res"),
        ],
        (Problem::DailyTemperatures, _) => vec![
            (1, "class Solution:"),
            (2, "    def dailyTemperatures(self, temperatures: List[int]) -> List[int]:"),
            (3, "        res = [0] * len(temperatures); stack = []"),
            (4, "        for i, t in enumerate(temperatures):"),
            (5, "            while stack and t > stack[-1][0]:"),
            (6, "                stackT, stackInd = stack.pop(); res[stackInd] = i - stackInd"),
            (7, "            stack.append((t, i))"),
            (8, "        return res"),
        ],
        (Problem::CarFleet, _) => vec![
            (1, "class Solution:"),
            (2, "    def carFleet(self, target: int, position: List[int], speed: List[int]) -> int:"),
            (3, "        pair = [(p, s) for p, s in zip(position, speed)]"),
            (4, "        pair.sort(reverse=True); stack = []"),
            (5, "        for p, s in pair:"),
            (6, "            stack.append((target - p) / s)"),
            (7, "            if len(stack) >= 2 and stack[-1] <= stack[-2]: stack.pop()"),
            (8, "        return len(stack)"),
        ],
        (Problem::LargestRectangle, _) => vec![
            (1, "class Solution:"),
            (2, "    def largestRectangleArea(self, heights: List[int]) -> int:"),
            (3, "        maxArea = 0; stack = []"),
            (4, "        for i, h in enumerate(heights):"),
            (5, "            start = i"),
            (6, "            while stack and stack[-1][1] > h:"),
            (7, "                index, height = stack.pop(); maxArea = max(maxArea, height * (i - index)); start = index"),
            (8, "            stack.append((start, h))"),
            (9, "        for i, h in stack: maxArea = max(maxArea, h * (len(heights) - i))"),
            (10, "        return maxArea"),
        ],
        (Problem::CharacterReplacement, _) => vec![
            (1, "class Solution:"),
            (2, "    def characterReplacement(self, s: str, k: int) -> int:"),
            (3, "        count = {}; res = 0; l = 0; maxf = 0"),
            (4, "        for r in range(len(s)):"),
            (5, "            count[s[r]] = 1 + count.get(s[r], 0); maxf = max(maxf, count[s[r]])"),
            (6, "            while (r - l + 1) - maxf > k:"),
            (7, "                count[s[l]] -= 1; l += 1"),
            (8, "            res = max(res, r - l + 1)"),
            (9, "        return res"),
        ],
        (Problem::PermutationInString, _) => vec![
            (1, "class Solution:"),
            (2, "    def checkInclusion(self, s1: str, s2: str) -> bool:"),
            (3, "        if len(s1) > len(s2): return False"),
            (4, "        s1Count, s2Count = [0] * 26, [0] * 26"),
            (5, "        for i in range(len(s1)): s1Count[ord(s1[i]) - 97] += 1; s2Count[ord(s2[i]) - 97] += 1"),
            (6, "        matches = sum(1 for i in range(26) if s1Count[i] == s2Count[i])"),
            (7, "        l = 0"),
            (8, "        for r in range(len(s1), len(s2)):"),
            (9, "            if matches == 26: return True"),
            (10, "            index = ord(s2[r]) - 97; s2Count[index] += 1"),
            (11, "            if s1Count[index] == s2Count[index]: matches += 1"),
            (12, "            elif s1Count[index] + 1 == s2Count[index]: matches -= 1"),
            (13, "            index = ord(s2[l]) - 97; s2Count[index] -= 1"),
            (14, "            if s1Count[index] == s2Count[index]: matches += 1"),
            (15, "            elif s1Count[index] == s2Count[index] + 1: matches -= 1"),
            (16, "            l += 1"),
            (17, "        return matches == 26"),
        ],
        (Problem::MinWindowSubstring, _) => vec![
            (1, "class Solution:"),
            (2, "    def minWindow(self, s: str, t: str) -> str:"),
            (3, "        if not t: return \"\""),
            (4, "        countT, window = {}, {}"),
            (5, "        for c in t: countT[c] = 1 + countT.get(c, 0)"),
            (6, "        have, need = 0, len(countT); res, resLen = [-1, -1], float(\"infinity\"); l = 0"),
            (7, "        for r in range(len(s)):"),
            (8, "            c = s[r]; window[c] = 1 + window.get(c, 0)"),
            (9, "            if c in countT and window[c] == countT[c]: have += 1"),
            (10, "            while have == need:"),
            (11, "                if (r - l + 1) < resLen: res = [l, r]; resLen = r - l + 1"),
            (12, "                window[s[l]] -= 1"),
            (13, "                if s[l] in countT and window[s[l]] < countT[s[l]]: have -= 1"),
            (14, "                l += 1"),
            (15, "        l, r = res; return s[l : r + 1] if resLen != float(\"infinity\") else \"\""),
        ],
        (Problem::SlidingWindowMax, _) => vec![
            (1, "class Solution:"),
            (2, "    def maxSlidingWindow(self, nums: List[int], k: int) -> List[int]:"),
            (3, "        output = []; q = collections.deque(); l = r = 0"),
            (4, "        while r < len(nums):"),
            (5, "            while q and nums[q[-1]] < nums[r]: q.pop()"),
            (6, "            q.append(r)"),
            (7, "            if l > q[0]: q.popleft()"),
            (8, "            if (r + 1) >= k: output.append(nums[q[0]]); l += 1"),
            (9, "            r += 1"),
            (10, "        return output"),
        ],
        _ => vec![(1, "# Approach implementation trace")],
    }
}

pub fn topk_code_lines() -> Vec<(usize, &'static str)> {
    vec![
        (1, "class Solution:"),
        (2, "    def topKFrequent(self, nums, k):"),
        (3, "        count = {}"),
        (4, "        freq = [[] for i in range(len(nums) + 1)]"),
        (5, ""),
        (6, "        for n in nums:"),
        (7, "            count[n] = 1 + count.get(n, 0)"),
        (8, "        for n, c in count.items():"),
        (9, "            freq[c].append(n)"),
        (10, ""),
        (11, "        res = []"),
        (12, "        for i in range(len(freq) - 1, 0, -1):"),
        (13, "            for n in freq[i]:"),
        (14, "                res.append(n)"),
        (15, "                if len(res) == k:"),
        (16, "                    return res"),
    ]
}

pub fn encode_decode_code_lines() -> Vec<(usize, &'static str)> {
    vec![
        (1, "class Solution:"),
        (2, "    def encode(self, strs):"),
        (3, "        res = \"\""),
        (4, "        for s in strs:"),
        (5, "            res += str(len(s)) + \"#\" + s"),
        (6, "        return res"),
        (7, ""),
        (8, "    def decode(self, s):"),
        (9, "        res = []"),
        (10, "        i = 0"),
        (11, "        while i < len(s):"),
        (12, "            j = i"),
        (13, "            while s[j] != \"#\":"),
        (14, "                j += 1"),
        (15, "            length = int(s[i:j])"),
        (16, "            res.append(s[j+1 : j+1+length])"),
        (17, "            i = j + 1 + length"),
        (18, "        return res"),
    ]
}

pub fn product_code_lines() -> Vec<(usize, &'static str)> {
    vec![
        (1, "class Solution:"),
        (2, "    def productExceptSelf(self, nums):"),
        (3, "        n = len(nums)"),
        (4, "        output = [1] * n"),
        (5, ""),
        (6, "        prefix = 1"),
        (7, "        for i in range(n):"),
        (8, "            output[i] = prefix"),
        (9, "            prefix *= nums[i]"),
        (10, ""),
        (11, "        suffix = 1"),
        (12, "        for i in range(n - 1, -1, -1):"),
        (13, "            output[i] *= suffix"),
        (14, "            suffix *= nums[i]"),
        (15, ""),
        (16, "        return output"),
    ]
}
